### ISSUE TITLE
Game Crashes using place unit menu (Ctrl+R or alt+R)

### ISSUE THREAD

**Issue by TheFlamelet** [wesnoth/wesnoth#10408]
### Game and System Information

- **Version:**1.19
- **OS:**Windows 

### Description of the bug

Game Crashes when browsing recruit menu.

### Steps to reproduce the behavior

1. R+alt or ctrl: open the recruit menu or open recall menu
2. type, search.
3. go into panic mode & press esc
4. Game will crash

### Expected behavior

No crash

### Additional context

Am I supposed to upload logs?

**Comment by Wedge009** [comment]
This was rather vague, but I managed to produce a crash - presumably the one you found - by the following (in 8cae493f464):

1. Start Wesnoth
2. Start a new campaign
3. Enter recruit dialogue
4. Enter enough characters in the search field to produce **zero** units.
5. Press Escape.
6. Segmentation fault

CC: @babaissarkar

**Comment by Wedge009** [comment]
Regression introduced in 3f774c10ca8dfccbc07149c19a396f76a4744369, presumably need to handle the case where no unit type is selected.

**Comment by sevu** [comment]
Crashes also when
- chat (alt+c) is open but empty, and one presses ESC
- debug create unit dialogue with 0 units listed and ESC

**Comment by Wedge009** [comment]
Debug create, recruit, and recall are all the same code now, so I think that's related. I'm not sure about chat - can you confirm that wasn't an issue previously?

**Comment by babaissarkar** [comment]
> Debug create, recruit, and recall are all the same code now, so I think that's related. I'm not sure about chat - can you confirm that wasn't an issue previously?

0eecbaa should fix the issue.

The issue turned out to be in the calling code for recruit and create (debug) dialogs (missing return when cancel pressed). Please see the fix commit.

**Comment by Wedge009** [comment]
@sevu If chat is still an issue, suggest you submit a separate report for that.

**Comment by sevu** [comment]
Alright
