### ISSUE TITLE
Pop Up Message of the Day (GNA #13398)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1158]
**[Original submission](https://gna.org/bugs/index.php?13398)** by blueblaze on 2009-04-19

Whenever a player joins the MP server, they are presented with a server side message of the day. The current MotD displays like a regular message from the chat, thus doesn't stand out as much as it deserves to. Another issue with the current MotD is that it is really limited to only a few lines of text while fitting on one screen. Because of these things, MotD tend to be cut short and not always fully providing important/help details about being on the server.

As a result, it would be nice to have a pop up message which displays the MotD. This message would be saved client side, and would only pop up whenever the player's message is outdated and in need of updating (which means it would trigger on first join too). Also, a possible extension of this might be to give the player the ability to call up the MotD via a /command.

(Reproduced on Any)
Release: 1.6.1
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-04-19**

**soliton changed status:** None -> Confirmed

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-04-19**

**soliton wrote:**

> "/query motd" already tells you the current motd.
> 
> 
> 
> I'm not completely sure whether a pop-up wouldn't be too annoying but saving the message (per server) and only showing it when it changed is a good idea.

**Comment by Wedge009** [comment]
Is there a MotD on the current server? 1.14

**Comment by soliton-** [comment]
Yes, there's a motd on all the servers we run.

**Comment by Wedge009** [comment]
I just used the /query motd command you listed 10 years ago... I didn't know that welcome message is supposed to be the MotD, I just thought it was a... welcome message.

I think it's pretty clear in the chat box when one first enters the lobby. I suppose it could be shown in a pop-up, if someone really wanted to have that kind of thign.

**Comment by soliton-** [comment]
I think paired with not showing the same message each time showing a pop-up could be good. Would make it easier to spot for example tournament announcements in the motd.

**Comment by Pentarctagon** [comment]
The ability to show the motd via a command already exists and not showing the same motd multiple times was fixed as of #4884.

Showing a popup I'd find kind of annoying though.

**Comment by soliton-** [comment]
With the #4884 changes I think this can be closed now and we'll see if issues remain or new ones pop-up with the new functionaility...
