### ISSUE TITLE
editor: quit dialog sometimes buggy (GNA #25286)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1601]
**[Original submission](https://gna.org/bugs/index.php?25286)** by matthiaskrgr on 2016-11-12

launch editor

hold down escape key for a bit (escape dialog should open and reclose a few times)

=>

now when I click "yes" in order to exit the editor, nothing happens, perhaps there is another instance of the escape dialog under it?

I have to confirm the same dialog another or 2 more times to actually exit the editor

(Reproduced on linux)
Release: v1.13.6+dev (3ff4a18-Clean)
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-13**

**vultraz wrote:**

> Can you see if this is still an issue? I cannot repro anymore.

**vultraz changed status:** None -> Works For Me

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-20**

**wedge009 changed status:** Works For Me -> Confirmed

**wedge009 wrote:**

> Weird. In Windows the exit dialogue only ever pops up once, so the issue doesn't happen. But in Linux, the Escape function keeps bringing up multiple instances of the exit dialogue, producing the issue mk described.
> 
> 
> 
> You might have to try this a few times, but I could not get this to happen in Windows, only Linux. Tested just now, against bd6a0c6.

**Comment by CelticMinstrel** [comment]
This should be fixed now.

**Comment by sevu** [comment]
I'm having sth. similar in my debug master build, although different.
If I press ESC for a while, the dialog remains, it doesn't close and pop up.
_If I click yes, I return immediately to the main menu._ 
If I click _no_, I have to do that eventually a few times.

In my optimized 1.13.8 build situation is as described above, despite that it doesn't only happen to _no_ but as well to _yes_

**Comment by matthiaskrgr** [comment]
This is still a problem // cc @CelticMinstrel 

I can reproduce by holding down escape while the editor is loading up (accessing via main menu)

My guess is that the game checks "if there already is a quit dialog, don't spawn a new one", however while the editor is not done loading, we build a queue of several quit dialogs that are to be rendered bypassing that check and ending up with several dialogs or something like that.

**Comment by CelticMinstrel** [comment]
I don't think there's any test for whether the quit dialog was open. As I understand it, the issue before was that the key down event was handled, which may include key repeats. The first one opens the quit dialog, but others are still queued, so once the quit dialog is closed, they retrigger it.

While the quit dialog is actually open, hitting escape doesn't open a quit dialog - instead, it cancels the quit dialog.

**Comment by Wedge009** [comment]
I missed the notification for this since I wasn't added in the move to GitHub. This is still an issue as of 057a5305, but still only for Linux.

**Comment by CelticMinstrel** [comment]
Is this still an issue?

**Comment by sevu** [comment]
Yes, 1.15.16.

After holding down the key a few sec it might happen that
-> there's no dialogue (last escape closed it)
-> One button (or key) press is enough (as expected).
-> Button (or key) must be pressed twice, once I even had thrice. Can be both the Yes or No button or even the ESC key to discard the dialogue.

Maybe it also happens on other platforms and it was not noticed? Can take quite a while to hit this case.

**Comment by Wedge009** [comment]
It's intermittent, but yes, still replicated on 1.17.0+dev under Linux. Still unable to encounter this in Windows, though.

**Comment by Wedge009** [comment]
I'm not able to replicate this any more, in 1.18/1.19 (checked in Linux). At a guess, the rendering overhaul probably removed the race condition that led to multiple quit dialogues being displayed. Holding down Esc key now, I get a flickering as the confirmation dialogue gets repeatedly shown and dismissed.
