### ISSUE TITLE
[set_menu_item] fires repeatedly if hotkey held down

### ISSUE THREAD

**Issue by ln-zookeeper** [wesnoth/wesnoth#1711]
If you assign a hotkey to a menu item, then that menu item will keep firing repeatedly (depending on your keyboard repeat delay/rate) if the hotkey is held down, of course assuming that the menu item actions themselves cause no interruption (such as a [message]).

Instead, a menu item should only fire once per keypress regardless of how long the key stays down, presumably rather on key pressed rather than key released.

Prompted by https://forums.wesnoth.org/viewtopic.php?t=46089

Easy to reproduce with for example the following:
```
    [event]
        name=start

        {VARIABLE i 1}

        [set_menu_item]
            id=hotkeymenuitemtest
            description="foo"
            use_hotkey=yes

            [default_hotkey]
                key=u
            [/default_hotkey]

            [command]
                [floating_text]
                    [filter]
                        side=1
                    [/filter]

                    text=$i
                [/floating_text]

                {VARIABLE_OP i add 1}
            [/command]
        [/set_menu_item]
    [/event]
```

**Comment by Vultraz** [comment]
Possibly shares a similar cause as #1601.

**Comment by CelticMinstrel** [comment]
This should be fixed now.

**Comment by Wedge009** [comment]
@CelticMinstrel Responding to IRC - I don't think I was ever able to test this one. Being WML related.

**Comment by Vultraz** [comment]
Just tested with this:
```
        {VARIABLE foo 0}
        [set_menu_item]
            id=footest
            description="footest"
                [default_hotkey]
            key=i
        [/default_hotkey]
            [command]
                {VARIABLE_OP foo add 1}
            [/command]
        [/set_menu_item]
```

The variable continues to increase as long as "i" is held down. Not fixed.

**Comment by CelticMinstrel** [comment]
Hmm, doesn't seem like my commit has been overwritten or anything, either...

https://github.com/wesnoth/wesnoth/blob/master/src/hotkey/hotkey_handler.cpp#L256

**Comment by jyrkive** [comment]
This is a regression from commit 92ca7fdb5eb11c04b191359892517ea22d9f4491.

`SDL_TEXTINPUT` events are considered as press events, and the OS generates such an event for every virtual keypress.

To fix this, I need to monitor `SDL_KEYDOWN` and `SDL_KEYUP` events, as well as event order.

**Comment by Wedge009** [comment]
Ouch, that was one of @Aginor's last commits, if I recall correctly.

**Comment by soliton-** [comment]
Also an important commit. We do want to continue to be able to tell people to use : to open the command line without having to know their keyboard layout.
