### ISSUE TITLE
Error when loading music with immediate = yes

### ISSUE THREAD

**Issue by tamanegi-jp** [wesnoth/wesnoth#1861]
In my campaign "A Group in a War" uploaded on 1.13.x addon server, the game crashes at the beginning of the second scenario (Outpost) as reported in the forum: https://forums.wesnoth.org/viewtopic.php?f=8&t=41451&p=615567#p615564
The crash happens on the music loading (lua) code in the preload event of the second scenario. This happens both on Linux and Mac (not checked on Windows). Sorry to say, I couldn't identify the exact cause of the crash so far.
Wesnoth version is: v1.13.8+dev (56990b17d9-Clean) (Jul 24, 2017).

As far as I can understand,
- calls of my lua code (Tamanegi Jukebox addon) in the first scenario (Prologue) maybe related to this crash (removing those codes suppresses crash)
- only [music] with "immediate = yes" causes the crash. (removing that line suppresses crash)
- if reloaded from the scenario beginning save file (Outpost; second scenario), it works correctly.

I guess something from the first scenario is not cleared correctly and then causes the crash on the second scenario. My guess might be incorrect,though.

backtrace of core is attached below. (died at impl_track_set in src/scripting/lua_audio.cpp)
```
(gdb) bt
#0  0x0000559d7a5d0820 in impl_track_set(lua_State*) ()
#1  0x0000559d7acb4f46 in luaD_precall(lua_State*, lua_TValue*, int) ()
#2  0x0000559d7acb5333 in luaD_call(lua_State*, lua_TValue*, int) ()
#3  0x0000559d7acc9cfc in luaT_callTM(lua_State*, lua_TValue const*, lua_TValue const*, lua_TValue const*, lua_TValue*, int) ()
#4  0x0000559d7accd909 in luaV_execute(lua_State*) ()
#5  0x0000559d7acb53b7 in luaD_callnoyield(lua_State*, lua_TValue*, int) ()
#6  0x0000559d7acb630c in luaD_pcall(lua_State*, void (*)(lua_State*, void*), void*, long, long) ()
#7  0x0000559d7acac7aa in lua_pcallk(lua_State*, int, int, int, long, int (*)(lua_State*, int, long)) ()
#8  0x0000559d7a5d6fa7 in luaW_pcall(lua_State*, int, int, bool) ()
#9  0x0000559d7a5c3826 in game_lua_kernel::run_wml_action(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, vconfig const&, game_events::queued_event const&) ()
#10 0x0000559d7ab8c4fb in game_events::event_handler::handle_event(game_events::queued_event const&, std::shared_ptr<game_events::event_handler>&, game_lua_kernel&) ()
#11 0x0000559d7a85c377 in game_events::wml_event_pump::process_event(std::shared_ptr<game_events::event_handler>&, game_events::queued_event const&) ()
#12 0x0000559d7a85c696 in std::_Function_handler<void (game_events::manager&, std::shared_ptr<game_events::event_handler>&), game_events::wml_event_pump::operator()()::{lambda(game_events::manager&, std::shared_ptr<game_events::event_handle---Type <return> to continue, or q <return> to quit---
r>&)#1}>::_M_invoke(std::_Any_data const&, game_events::manager&, std::shared_ptr<game_events::event_handler>&) ()
#13 0x0000559d7a853185 in game_events::manager::execute_on_events(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (game_events::manager&, std::shared_ptr<game_events::event_handler>&)>) ()
#14 0x0000559d7a860f7c in game_events::wml_event_pump::operator()() ()
#15 0x0000559d7a86186e in game_events::wml_event_pump::fire(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, game_events::entity_location const&, game_events::entity_location const&, config const&) ()
#16 0x0000559d7aa41316 in play_controller::fire_preload() ()
#17 0x0000559d7aa44302 in play_controller::start_game() ()
#18 0x0000559d7aa4df5a in playsingle_controller::play_scenario_init() ()
#19 0x0000559d7aa50b55 in playsingle_controller::play_scenario(config const&)
    ()
#20 0x0000559d7a87166c in campaign_controller::playsingle_scenario(end_level_data&) ()
#21 0x0000559d7a871a63 in campaign_controller::play_game() ()
#22 0x0000559d7a47eb47 in game_launcher::launch_game(game_launcher::RELOAD_GAME_DATA) ()
#23 0x0000559d7a40fe3b in main ()
```

**Comment by CelticMinstrel** [comment]
From a glance at the code, this crash cannot possibly be caused by a `[music]` tag - the `impl_track_set` on top of that stack trace is only called from Lua code of the form `wesnoth.music_list[i] = {...}`, which does not exist in the Lua implementation of the `[music]` tag.

I can however see a likely reason for the crash, though, so I'll attempt to address it.

**Comment by tamanegi-jp** [comment]
The segfault no longer happens and an error message
`Error: Attempted to access an invalid music track.`
is shown instead. (This error message is not shown if restarted from the scenario beginning save file. This is the same as before.)

In addition, I found that the crash (or the error message above) disappears by replacing the following line
```
wesnoth.set_music { name = music_list[numbers[i]].file, immediate = true }
```
into
```
wesnoth.music_list.play(music_list[numbers[i]].file)
wesnoth.set_music { name = music_list[numbers[i]].file }
```
I cannot find any meaningful differences between them, though.

(I'm not sure whether this issue should be closed...)

**Comment by CelticMinstrel** [comment]
Is `music_list` the same as `wesnoth.music_list` in this code? I think you could get this error if `numbers[i]` were outside the range of the current playlist, ie negative, zero, or greater than `len(wesnoth.music_list)`.

I'll note that `wesnoth.set_music` is deprecated, though. If I recall correctly, it's now just a stub that forwards its arguments to `wesnoth.wml_actions.music`, so you could call that instead, or you could use the new music API under `wesnoth.music_list`. To play a track immediately, you would call `wesnoth.music_list.play(track_name, true)`.

**Comment by tamanegi-jp** [comment]
That `music_list` is a local variable, not the same as `wesnoth.music_list`. If the array index is out of range (`music_list[0]` or `music_list[100]` for example), different error message is shown; `error scripting/lua: ~add-ons/Tamanegi_Jukebox/lua/jukebox.lua:203: attempt to index a nil value (field '?')`.

Anyway, I found the problem. In the following part of wml_actions.music function in wml-tags.lua, `wesnoth.music_list.current.once = true` code which locates inside `cfg.immediate` conditonal triggers the error.
```
                        if cfg.immediate then
                                wesnoth.music_list.current.once = true
                        end
                        wesnoth.music_list.clear()
```

If i avoided this current.once = true code, everything work fine at least for me. I dunno what is really going on, though.

In my specific case, "current track" when the error occurs is a `play_once = yes` track from the previous scenario (`wesnoth.music_list.current` seems not to be nil and `wesnoth.music_list.current.once` seems to be true). It might be related to the issue...?

(Thank you for your advice about `wesnoth.set_music`, I will replace them to wml_actions.music or something similar. :) )

**Comment by CelticMinstrel** [comment]
So you're saying that `wesnoth.music_list.current` is nil, yet there's a track playing? This should never happen.

**Comment by tamanegi-jp** [comment]
My writing might be confusing. `wesnoth.music_list.current` seems NOT to be nil. It's not nil.

**Comment by CelticMinstrel** [comment]
Oh, maybe I just misread your post, sorry.

Hmm, looking at that code, I suppose it should actually check if current is nil before doing that... but I guess that's not what's causing your issue, since you're getting the new "accessed invalid track" error, which implies something fishy in the reference to the track stored in the Lua engine...

**Comment by tamanegi-jp** [comment]
Anyway, the crash itself is already fixed by your recent commit. Fortunately or unfortunately, only I am affected by this issue, and this issue can be avoided by some tricks. So I think the severity of this issue is significantly lowered. IMHO, you can remove the blocker tag and wait for another (more clear) report...

If I succeeded in preparing minimal example, I will upload it.

**Comment by CelticMinstrel** [comment]
Yeah, I was thinking about removing the blocker tag but leaving the issue open; although I fixed the crash, the bug still remains.

**Comment by Pentarctagon** [comment]
I'm not sure if this is the same issue or not, but I can reproduce the `Error: Attempted to access an invalid music track.` message with the below code:
```
[event]
  name="turn 1"

  [music]
      name=knolls.ogg
      ms_before=12000
#        immediate=yes
  [/music]
  [lua]
    code=<<
      wesnoth.music_list.current.__index = true
    >>
  [/lua]
[/event]
```

The [music] tag is just the first one in the `DEFAULT_MUSIC_PLAYLIST` macro.  Though in this case, adding `immediate=yes` actually prevents the invalid playlist message from appearing.

The full message is:
```
20170929 16:15:25 error scripting/lua: [string "..."]:2: Error: Attempted to access an invalid music track.

stack traceback:
	[C]: in metamethod '__newindex'
	[string "..."]:2: in local 'bytecode'
	lua/wml-tags.lua:282: in local 'cmd'
	lua/wml-utils.lua:145: in field 'handle_event_commands'
	lua/wml-flow.lua:6: in function <lua/wml-flow.lua:5>
```

**Comment by Arcanister** [comment]
So, did you finally find a way to reproduce #2010  reliably?

**Comment by Pentarctagon** [comment]
Maybe; the tracebacks don't quite match though.  My guess is that these are all in some way related to somehow the playlist being accessed while it's in the process of being updated/started, though, since both this as #2010 mention happening at the beginning of a scenario, when the default playlist that was started on the main menu is replaced by another playlist.

**Comment by AI0867** [comment]
I can't reproduce it with Pentarctagon's WML, with or without the immediate=yes.

**Comment by Pentarctagon** [comment]
Err.. whoops.  Turns out my own music player modification was active, and that was affecting it as well.  The below code should be able to cause the error message on its own:
```
[event]
  name="turn 1"

	[music]
		append=no
		immediate=yes
		name="knolls.ogg"
		play_once=no
		shuffle=yes
	[/music]
	[music]
		append=yes
		immediate=yes
		name="wanderer.ogg"
		play_once=no
		shuffle=yes
	[/music]
	[music]
		append=yes
		immediate=yes
		name="battle.ogg"
		play_once=no
		shuffle=yes
	[/music]
	[music]
		append=yes
		immediate=yes
		name="transience.ogg"
		play_once=no
		shuffle=yes
	[/music]
	[music]
		append=yes
		immediate=yes
		name="the_king_is_dead.ogg"
		play_once=no
		shuffle=yes
	[/music]
	[music]
		append=yes
		immediate=yes
		name="knalgan_theme.ogg"
		play_once=no
		shuffle=yes
	[/music]
	[music]
		append=yes
		immediate=yes
		name="the_city_falls.ogg"
		play_once=no
		shuffle=yes
	[/music]
	[music]
		append=yes
		immediate=yes
		name="nunc_dimittis.ogg"
		play_once=no
		shuffle=yes
	[/music]
	[music]
		append=yes
		immediate=yes
		name="revelation.ogg"
		play_once=no
		shuffle=yes
	[/music]
	[music]
		append=yes
		immediate=yes
		name="loyalists.ogg"
		play_once=no
		shuffle=yes
	[/music]
	[music]
		append=yes
		immediate=yes
		name="breaking_the_chains.ogg"
		play_once=no
		shuffle=yes
	[/music]
	[music]
		append=yes
		immediate=yes
		name="elvish-theme.ogg"
		play_once=no
		shuffle=yes
	[/music]
	[music]
		append=yes
		immediate=yes
		name="legends_of_the_north.ogg"
		play_once=no
		shuffle=yes
	[/music]
	[music]
		append=yes
		immediate=yes
		name="traveling_minstrels.ogg"
		play_once=no
		shuffle=yes
	[/music]
	[music]
		append=yes
		immediate=yes
		name="underground.ogg"
		play_once=no
		shuffle=yes
	[/music]
	[music]
		append=yes
		immediate=yes
		name="vengeful.ogg"
		play_once=no
		shuffle=yes
	[/music]
	[music]
		append=yes
		immediate=yes
		name="frantic.ogg"
		play_once=no
		shuffle=yes
	[/music]
	[music]
		append=yes
		immediate=yes
		name="the_dangerous_symphony.ogg"
		play_once=no
		shuffle=yes
	[/music]
	[music]
		append=yes
		immediate=yes
		name="heroes_rite.ogg"
		play_once=no
		shuffle=yes
	[/music]
	[music]
		append=yes
		immediate=yes
		name="suspense.ogg"
		play_once=no
		shuffle=yes
	[/music]
	[music]
		append=yes
		immediate=yes
		name="the_deep_path.ogg"
		play_once=no
		shuffle=yes
	[/music]
	[music]
		append=yes
		immediate=yes
		name="siege_of_laurelmor.ogg"
		play_once=no
		shuffle=yes
	[/music]
	[music]
		append=yes
		immediate=yes
		name="casualties_of_war.ogg"
		play_once=no
		shuffle=yes
	[/music]
	[music]
		append=yes
		immediate=yes
		name="silvan_sanctuary.ogg"
		play_once=no
		shuffle=yes
	[/music]
	[music]
		append=yes
		immediate=yes
		name="battle-epic.ogg"
		play_once=no
		shuffle=yes
	[/music]

  [music]
      name=knolls.ogg
      ms_before=12000
#        immediate=yes
  [/music]
  [lua]
    code=<<
      
      local l = wesnoth.music_list.current.__index
    >>
  [/lua]
[/event]
```

Also interestingly, a smaller initial playlist does not cause an error message to appear:
```
[event]
  name="turn 1"

	[music]
		append=no
		immediate=yes
		name="knolls.ogg"
		play_once=no
		shuffle=yes
	[/music]

  [music]
      name=knolls.ogg
      ms_before=12000
#        immediate=yes
  [/music]
  [lua]
    code=<<
      
      local l = wesnoth.music_list.current.__index
    >>
  [/lua]
[/event]
```

**Comment by AI0867** [comment]
I've managed to trace it to the lua_music_track::lua_music_track(int i) constructor. In this particular case, it gets called with an argument of 24, while the number of tracks in the playlist is 1. sound::get_track(int) then returns a shared_ptr to nullptr.

**Comment by CelticMinstrel** [comment]
So the next question is, why is it being called with an argument of 24...

**Comment by Pentarctagon** [comment]
The first playlist has 25 songs, so I'd guess that the playlist information has been updated to the second playlist with 1 song while the lua part still thinks there's 25 songs.

**Comment by AI0867** [comment]
The problem seems to be that the internal variable `current_track_index`, which can contain a value equal to the size of the track list, is exposed through `get_current_track`, and callers assume that this index must be valid.

Something similar seems to have happened before: a2da2d5fdeea50a846d2e239ec8ae3058cdf6092
