### ISSUE TITLE
Trait loyal & aged bugs in Help

### ISSUE THREAD

**Issue by sigurdfdragon** [wesnoth/wesnoth#1935]
In the traits section in help:

loyal is listed as must_have
aged is missing

Aged used to be showing, but it's likely the changes to a generated trait list caused it to be dropped.
Took a look, couldn't figure out what was going on.

**Comment by Wedge009** [comment]
I don't even have loyal any more, in my master build. I have:
- dextrous
- dim
- elemental
- fearless
- feral
- healthy
- intelligent
- mechanical
- quick
- resilient
- slow
- strong
- undead
- weak

Contrast with 1.12, where I have an unsorted list consisting of:
- Fearless
- Intelligent
- Resilient
- Strong
- Quick
- Dextrous
- Healthy
- Dim
- Slow
- Weak
- Feral
- **Loyal**
- Undead
- Mechanical
- Elemental
- **Aged**

I've emboldened the ones which don't currently show in master.

**Comment by CelticMinstrel** [comment]
My suggestion would be to add the loyal and aged traits to the fog clearer unit, allowing them to be detected by the generation code.

**Comment by sigurdfdragon** [comment]
@CelticMinstrel Ok, I'll add them to the fog cleaner in day or two.

Loyal was showing for me because I had a custom unit I gave a loyal musthave to. Using the -noaddons switch I get the same as @Wedge009

**Comment by sigurdfdragon** [comment]
Fixed in https://github.com/wesnoth/wesnoth/commit/aac09417bff0240f90fd29d9fe0e037605a593d0

**Comment by Wedge009** [comment]
Hmm, I just did a fresh recompile and also confirm that my 'fog clearer' unit has the new traits added, but I still don't see aged or loyal in the Help. Am I missing something?

**Comment by sigurdfdragon** [comment]
Clear cache maybe? It's working for me.

**Comment by Wedge009** [comment]
It must be related to the preferences file somehow (encountered units?). I cleared the <userdata>/cache/ directory and got no change. I cleared the preferences file and now only have intelligent, quick, resilient, and strong.

**Comment by sigurdfdragon** [comment]
I think so. when I throw out the pref file, I get same as you. When I launch in debug mode with a fresh prefs, all the traits are there

**Comment by Wedge009** [comment]
Confirming aged and loyal are present in debug mode. That's good enough for me. Thanks.
