### ISSUE TITLE
wesnoth-s `print` is incompatible with normal lua `print`

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2236]
Steps to reproduce:
* execute this in wesnoth: `print("test", true)`
* execute this in "OS" lua: `print("test", true)`

Expected:
similar or identical output

Actually:
* First line prints `test`
* Second line prints `test	true`

**Comment by vgaming** [comment]
On IRC chat, JyrkiVesterinen pointed this to be the possible buggy implementation of `print`: https://github.com/wesnoth/wesnoth/blob/master/src/scripting/lua_kernel_base.cpp#L94-L119

**Comment by GregoryLundberg** [comment]
Not buggy but it can be improved.

Wesnoth depends upon loa_tostring obtaining a string value.

The Lua version calls into the Lua runtime to `tostring(..)` to do the conversion, then uses lua_tostring to obtain the result.

Give me a few hours ...

**Comment by kallaballa** [comment]
oh.. i didn't see that you already assigned the issue to you. in the meanwhile i fixed the bug: https://github.com/kallaballa/wesnoth/commit/49d1055abed65b57a54ebb012c92e8894659d87a

Should i create a PR?

**Comment by GregoryLundberg** [comment]
If you compare, I think you'll see you missed a lot of cases.

**Comment by kallaballa** [comment]
You are right, though i see only one case: user data

**Comment by GregoryLundberg** [comment]
boolean, table, userdata, function, thread ...
