### ISSUE TITLE
Inaccurate comment to div100rounded()

### ISSUE THREAD

**Issue by thblack** [wesnoth/wesnoth#2330]
Version: 1.13 current (GitHub, 27 Dec. 2017)
File: src/utils/math.hpp
Lines: 49 through 52
Priority to fix: low
Difficulty to fix: low
Fix included with this report: yes

The file src/utils/math.hpp seems to harbor an inaccurate comment.

    /** Guarantees portable results for division by 100; round towards 0 */
    inline int div100rounded(int num) {
            return (num < 0) ? -(((-num) + 50) / 100) : (num + 50) / 100;
    }

I would recommend that the words "round towards 0" be changed to "round away from 0".

Not recommended: the logic (rather than the comment) could be changed to round towards 0, which was probably the programmer's original intent. However, as far as I can tell, such a change would alter gameplay without improving it.

The code in question affects a unit's quick trait. Quickness costs a unit one hit point if the unit's base lies in the range [10 to 29], costs a unit two hit points if its base lies in the range [30 to 49], costs a unit three hit points if its base lies in the range [50 to 69], and so on. The quick trait interacts with the resilient and strong traits in this; but anyway, as far as I know, the code is working well. Only the comment is wrong.

To reproduce the effect, recruit an elvish archer, at 29 base hit points, and a merman hunter, at 30 base hit points. Observe that the quick and intelligent traits equalize these two units at 28 hit points each. This is an effect of div100rounded().

Incidentally, div100rounded() and the related round_damage() are well-written code. Some programmers would have abused floating-point arithmetic to shortcut this code, but the way it is written is the right way to write it. The code works in integers, just as it ought to do.

It is not important to fix the bug in version 1.12 as far as I know, but you can fix it in version 1.13 when you have some time.

**Comment by GregoryLundberg** [comment]
Personally, every time I look at math.?pp I cringe. It's not so much that the half-bit work is wrong as, after decades of dealing with junior programmers, I naturally assume it's wrong and I really don't like having to do a formal proof just because the comments (where they exist) don't match the code.

The chances of anything causing a 1.12 version release are a good approximation of zero.

I, or someone, will check your work and commit a correction if needed. Thanks for the report.

**Comment by gfgtdf** [comment]
this was clearly borken by this commit https://github.com/wesnoth/wesnoth/commit/3d580f1ab889d6554e38af480623dfcebbdfb053

**Comment by thblack** [comment]
@gfgtdf: isn't that interesting? Well, the bug report stands, but my recommended fix may be irrelevant.

**Comment by gfgtdf** [comment]
it's somhow unfortunate that the commit above offers no hint why it changed div100rounded in the first place. I have to assume that the author was just unable to read simple code comments, so i'd vote for changing it back to 49.

that woudl then also changes the apply_effect function round towards current values as it should .

a sperate issues is that unfutunately this is still not handled consistently in the wesnoth codebase, that is hitpoints might be rounded differently that movment point modifers

**Comment by GregoryLundberg** [comment]
(1) The commit is clearly because someone noticed that at exactly 1/2 it rounded wrong. Bravo.

(2) The comment was the same 7 years ago as it is today. Boo Hiss.

The question is negative values. The reason for the function is to ensure that division by 100 rounds the same on a one's compliment machine as it does on a two's compliment machine. The fiddling with negative numbers in the existing code is telling me that rounding as on a one's compliment machine is the desired form.

Expected results table:
```
-99 through -50 round to -100 (range 50 values)
-49 through    0 round to      0 (range 50 values)
   0 through  49 round to      0 (range 50 values)
 50 through  99 round to  100 (range 50 values)
```
The code properly implements this.

The OP's comment is that the phrase 'away from' should be 'toward' zero.

My feeling is the correct action is to simply eliminate the comment from the source.

Jeez we're wasting a LOT of time over a poorly-worded comment.

**Comment by gfgtdf** [comment]
> (1) The commit is clearly because someone noticed that at exactly 1/2 it rounded wrong. Bravo.

so you are saying that even before that commit the rounding was wrong?

> Expected results table:

why woudl these results be exepcted?

**Comment by GregoryLundberg** [comment]
I expect them from reading the code. Any, yes, to comment/code issue was before the 49/50 bug was corrected by that commit.

It was the expected results table from the code which made me go "aha! they're worring about one's vs two's compliment integer divide"

**Comment by gfgtdf** [comment]
sry but i still don't see why you think that commit imprtoved things, the comment above the function (and the commit that write that function) clearly says round towards zero, that means 50 is rounded to zero, and the code before that new commit did erxactly that, after that new commit 50 is rounded to 1 which is then wrong, specially since it offers no hint why rounding towards 50 woudl be better in that context where the function is used.

**Comment by GregoryLundberg** [comment]
Before that commit:
```
 -99 through -51 round to -100 (range 49 values)
 -50 through   0 round to    0 (range 51 values)
   0 through  50 round to    0 (range 51 values)
  51 through  99 round to  100 (range 49 values)
```

**Comment by gfgtdf** [comment]
yes, so?

**Comment by gfgtdf** [comment]
i mean if i understood corecrly your argumentation somwhow seems to be based on the `range 49 values` part of your data, but the that range just seem to be chosen arbitiary, you end your range at 99 and then say the latest part has only 49 elements, by the same argumentation you could put the 100 in, throw the 0 out and then say in the old methog the range `1 to 49 is rounded to 0 (49 elements), 50 to 100 is rounded to 100 (51 elements)`

**Comment by GregoryLundberg** [comment]
Consider the values as modulo 100. They're the fractional part (times 100) only from the fix-point integer value coming into the function. So 2349 -> 49, -314 -> -14, to look up the result in my table.

The point being that on some machines -150/100 becomes (-1 remainder -50) and on others it becomes (-2 remainder 50) and this code is to work around the difference.

Basically, it's a hold-over from when non-Intel x86 machines where supported.

**Comment by thblack** [comment]
For information, the related function round_damage(), next in the source, rounds toward zero. That is, round_damage() acts inconsistently with the current div100rounded().

I express no opinion but only give information.

**Comment by gfgtdf** [comment]
> Consider the values as modulo 100 to look up the result in my table.

uhm no why shodul i it makes zero sense in this context.

> The point being that on some machines -150/100 becomes (-1 remainder -50) and on others it becomes (-2 remainder 50) and this code is to work around the difference.

well, partly: The main point of this function is to rounds towards zero, and to so this in a save way we have to work aroung the negative numbers issue, but this doesn't mean that runing tiwards zero is wrong.

**Comment by GregoryLundberg** [comment]
'Towards zero' makes no sense to me. 'To the nearest integer' makes a lot of sense.

The input `num` is a fixed-point integer which, when converted to decimal, has two decimal digits to the right of the decimal point. The function divides `num` by 100 to convert it to a normal `int` value. It does so in a way which is consistent regardless of whether the execution machine is one's or two's compliment.

So, consider the value `num=2350` add 50 to get `num=2400` then divide by 100 to get the result 24. "The value 23.50 is rounded to 24"

Under the old code, the value 23.51 rounded to 24 but the value 23.50 rounded to 23. The commit adjusted it so that the down/up was at 49/50 instead of 50/51 and I would suggest it is more correct because after the change, exactly half the results round down and half round up. My guess is that it was spotted when doing a gold calculation and the assumption was that all uses of the function needed it to split 50/50 instead of 51/49.

As I said, "towards zero" makes no sense to me. I see it as "to the closes integer" which is the comment the OP points to in the next function. (Which I'm still trying to figure out but, at this point, it looks like it MUST NOT be given any negative values for any of the three parameters).

**Comment by soliton-** [comment]
23.5 is exactly between 23 and 24. I don‘t see anything inherently logical about rounding it up or down.

The commit changing the rounding certainly looks suspicious with no reason given for the change. It would have been enough to just switch to the rounding function from the previous truncation.

**Comment by GregoryLundberg** [comment]
@soliton- You're thinking in real numbers.  It's not 23.50 it's 2350, an integer, and there are 50 values from 0 to 49, including 0 and 49, and 50 from 50 to 100(0), including 50 and 100(0).  Prior to the patch there were 51 values from 0 to 50, including 0 and 50, and 49 values from 51 to 100(0), including 51 and 100(0). The patch from 7 years ago is correct.

**Comment by thblack** [comment]
The original programmer might have had another motive. He might have intended _to tip 0.5 toward default._

Details follow.

Before reporting, I had some time to think. I lack an opinion but have a surmise. My surmise admittedly differs from Gregory's (though his observation re two's complement is interesting).

I surmise that the original programmer intended _to tip 0.5 toward default._ I surmise that, later, commit [3d580f1](https://github.com/wesnoth/wesnoth/commit/3d580f1ab889d6554e38af480623dfcebbdfb053) inadvertently broke the original programmer's intent.

I surmise that the original programmer was not thinking of two's complement. Like Gregory, I too tend to think in terms of two's complement, but my reading of the code suggests to me that that might not be what the original programmer had in mind.

Example: charging, a horseman's lance does 18 points of damage. Daytime, conferring a +25% bonus, would raise this damage to 22.5 points. What to do with the 0.5? Round up or round down?

If I surmise rightly, then the original programmer had reasoned, "Well, 18 points is the default, after all. When in doubt, let's just round toward 18 points." At any rate, working in integer arithmetic, that is what the function round_damage() actually does.

Until the commit in question, the function div100rounded() did likewise. It too tipped 0.5 toward default. Since the commit, it tips 0.5 away from default, whereas round_damage() still tips toward.

**Comment by GregoryLundberg** [comment]
This is why I hate mixed commits and lame or missing commit messages. If we want to talk about intent, then let's assume the intent was to fix one thing and it took two parts. The first was to replace an `int` divide ` / 100` with the call to the function. The second, to me, was more "Oh, look, an off-by-one, let's just fix that."

Assuming all values are equally likely, I seriously doubt anyone, ever, thought "Let's skew this 1% toward a lower value." But I could certainly see the commit noting the off-by-one and thinking "Nah, let's not have that 1% skew to one less gold." Given the nature of the gold change, I'd guess an MP game came up with just the right values that one player got the 1 more gold than the other.

All this is neither here nor there. I take the code and correct and my PR adjusts the comment to remove the issue. Let's stop wasting time on the issue. If nobody seriously objects in the next few days, I'll merge it. In the meantime, I'm more worried that MP Moderation was never implemented and we're supposed to be in late beta for 1.14, ready for a release candidate.

**Comment by Ja-MiT** [comment]
If the focus of this issue is supposed to be the comment, a better commit to look at would be fd25958376a648010838df7d7427122b18250867. This commit renamed the function `div100` to `div100rounded` and changed the functionality so that it rounded to the nearest integer instead of always rounding to zero (a.k.a. truncating). So far, not bad, as the name change matches the functional change. However, this commit also changed the comment in question by adding the "round towards 0" part, which interestingly ceased to be true as of the same commit.

Anyway, my main point is to agree with @GregoryLundberg that neither "round towards 0" nor "round away from 0" accurately describes the current code. Those phrases suggest that the fractional part does not matter, yet it does matter. Also, @thblack may be interested to know that this commit I brought up is called "unit mods now round towards original value instead of truncating". (It's still not the origin of the "remov[al] of some non-portable divisions", though -- see c8b88fae5d27c0f6c1322d3b375d6cb5188b1fab.)

Whether the code rounds `50/100` through `149/100` to `1`, or rounds `51/100` through `150/100` to `1` is, from a mathematical viewpoint, largely inconsequential as long as there is consistency. In either case, the range consists of `100/100` plus 49 values on one side and 50 on the other. You cannot get a more even split while dealing with integers.

**Comment by gfgtdf** [comment]
> Anyway, my main point is to agree with @GregoryLundberg that neither "round towards 0" nor "round away from 0" accurately describes the current code. Those phrases suggest that the fractional part does not matter

Well ok so in eigher case we have to update those comment, to eigher say 'Round _half_ to zero' or 'Round _half_ away from zero'. Still i think rounging halp torards zero is better here.

> Assuming all values are equally likely, I seriously doubt anyone, ever, thought "Let's skew this 1% toward a lower value."

but we have 99 values btween 0 and 100 an .. liek liek jamit said in his last comment

>But I could certainly see the commit noting the off-by-one and thinking "Nah, let's not have that 1% skew to one less gold

The _main_ usecase for that function is is not theat carryover gold, it's the apply modifer function that in particuar handles most stat changes by objects.

**Comment by GregoryLundberg** [comment]
:eyeroll:

The range is 00 to 99 and there are 100 values there, not 99.

If you want to count the inter-value spaces, you'll get 99, and if you choose the mid-point between __those__ you'll still wind up using 50 since it's half-way, between the 49-50 space and the 50-51 space.

We're not talking about the main use case, we're speculating as to why and how the commit chose to (correctly) correct the mid-point from 49 to 50. The OP discussed having done extensive testing to ensure himself that change was correct. Do you have any use cases where skewing the odds off "even odds for all cases" makes sense? And, if so, should there be two functions: one skewed and one not?

**Comment by gfgtdf** [comment]
> The range is 00 to 99 and there are 100 values there, not 99.

not it's not, the range is form 1 to 99. it makes zero sense to include the 0, not the 100 and then say the 50 houdl belong to the upper range becsue the first range alrady contaisn the 0. please eigher think about it, read the wikipedia page on rounding or do whatever else to inform youself , and then post.

**Comment by GregoryLundberg** [comment]
Read the Wikipedia page. The function was written as "round half up" but originally used the incorrect value of 0.49 instead of 0.5 as given in the Wikipedia page. So, the 7-year-old commit is correct, the comment was wrong and I'll accept that I should change my comment change PR to read "round half-up, to the nearest integer"

Case closed.

**Comment by gfgtdf** [comment]
not it's not, the original function was round-half-down and used the correct 49 value for that, and that wikipedie article is about reals where the 49 was obviously won't work,  integers `n` are _not_ representatives for the real range `[n, n+1[` (or `[n, n+1)`, whatever you notation you used at scool) they are just numbers, thats also why betwwen 0 and 100 there are exactly 99 numbers (or 101 numbers if you are asking for between-or-equal)

**Comment by GregoryLundberg** [comment]
I'm looking at [Wikipedia 'rounding'](https://en.wikipedia.org/wiki/Rounding) and don't see 0.49 anywhere. (In fact, search the page and the string '49' does not appear anywhere.)
Round half-up adds 0.5 to positive values. Round half-down subtracts 0.5 from positive values.

The original code, prior to the commit 7 years ago added 0.49 to positive values. That is "round a-bit-less-than-half up". For evenly distributed random values it introduced a 1% bias toward the smaller integer rather than the goal of an unbiased rounding. While it's possible someone actually noted the bias during normal play, my guess is the author of the commit simply noted the non-standard rounding system and corrected it.

You can keep claiming the old code was correct. But to use a non-standard rounding system, you'll have show why none of the standard systems won't do.

**Comment by gfgtdf** [comment]
> I'm looking at Wikipedia 'rounding' and don't see 0.49 anywhere. (In fact, search the page and the string '49' does not appear anywhere.)

of course not,  that 49 only works on integers, in paticular it is specific to rounded division by 100. 

if you take that definition from round half towards zero from that refernced page it says `ceil(x - 0.5)` (for `x>=0`), in our context that'd be `ceil_100(x - 50)` which is _exactly_the_same_ as `floor_100(x + 49)` whihc is what the old code did.
