### ISSUE TITLE
Liberty - Comma after 'Concealment' Ability in the unit description of Borderer (base unit Fugitive)

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3060]
~Bandit/Highwayman/Village Elder/Senior Village Elder Baldras is using a mace instead of a morning star and and Outlaw/Fugitive/Watchman/Border Harper is using a club instead of a morning star.
[Liberty-A Strategy of Hope-Auto-Save1.gz](https://github.com/wesnoth/wesnoth/files/1986891/Liberty-A.Strategy.of.Hope-Auto-Save1.gz)
[Liberty-Civil Disobedience-Auto-Save11.gz](https://github.com/wesnoth/wesnoth/files/1986892/Liberty-Civil.Disobedience-Auto-Save11.gz)
![harper](https://user-images.githubusercontent.com/39015360/39803391-3389ad50-5371-11e8-9387-6e297a45319f.png)~

Also, there is a comma behind 'concealment' in the unit description of borderer.
![comma](https://user-images.githubusercontent.com/39015360/39803401-38a0a8c0-5371-11e8-91ab-9b8a0ead3595.png)

**Comment by sevu** [comment]
The raison d'etre are the portraits for Baldras and Harper, they have different weapons there.
We can only match the portraits _or_ the sprites.

**Comment by Konrad22** [comment]
Thanks for the explanation.
Should I close this issue or leave it open because of that comma?

**Comment by sevu** [comment]
As for the comma - the borderer inherits the first ability and adds as second this _nameless_ one
```
    [abilities]
        [outlaw_type_hack]
            id=Fugitive
        [/outlaw_type_hack]
    [/abilities]
```
Apparently it's correctly hidden if there are no other abilities involved.

There was some years ago a similar case for traits, and it does not add a comma for nameless traits - maybe that code can be reused?

@gfgtdf, maybe you know more

**Comment by gfgtdf** [comment]
> Apparently it's correctly hidden if there are no other abilities involved.

well ther is no comma generated when there is only one ability, inspended to whetehr that ability has an empty name  or not.

> @gfgtdf, maybe you know more

I feel like this was already repoted somehere, but i don't rmember where exactly unfrunateley. Iirc @Vultraz recently refactored the way help display its abilitites see also https://github.com/wesnoth/wesnoth/issues/2907 so it was probably the same commit that broke this one.

**Comment by Wedge009** [comment]
Not too long ago the abilities were not showing up at all, but that bug was since resolved, or so I believed. Is it the case that the second 'invisible' ability is causing the comma where it shouldn't be?

**Comment by Konrad22** [comment]
(I think it's noteworthy that this bug appear in Borderer (modified unit), but not in Fugitive (base unit).)

**Comment by CelticMinstrel** [comment]
I'd say that units without a translatable name should probably not be listed at all.

**Comment by sevu** [comment]
Summing up:
No abilities -> no problem
Normal abilities -> no problem
One hidden ability only -> no problem
Multiple hidden abilities -> no problem
Normal + hidden ability -> comma inserted for the hidden one


I looked up the commits for the traits fix: dc2b40f  
  

@Konrad22 
> (I think it's noteworthy that this bug appears in Borderer (modified unit), but not in Fugitive (base unit).)

This is due to the code I posted above. The unit did inherit from the base unit the one ability, and got a 2nd one additional. The other units have only this one.

**Comment by sevu** [comment]
I updated my last comment, I wrote completely wrong information before.

**Comment by sevu** [comment]
Fixed by #3354

**Comment by jostephd** [comment]
@sevu Thanks for your diligence, but #3354 doesn't fix this. It only affects ability topics, not unit topics. Please reopen.

The code causing this issue is `unit_topic_generator::operator()()`.

**Comment by sevu** [comment]
Ah, I missed that.

**Comment by Wedge009** [comment]
@nemaara This appears to be specific to the Borderer unit in Liberty. The base Fugitive doesn't have this issue.

**Comment by jostephd** [comment]
@Wedge009 Yes, but the bug isn't in campaign code, it's in the C++ help code. UMC would be affected too, for example.
