### ISSUE TITLE
Wesnoth dumps core when run in fullscreen.

### ISSUE THREAD

**Issue by Phenitei** [wesnoth/wesnoth#3716]
Hi,

I am using wesnoth on archlinux and run into trouble when trying to run wesnoth in fullscreen. Everything behaves normally when wesnoth is started with the windowed (`-w`) mode. Wesnoth was installed through the distribution's package manager. Relevant information:

* System:
```
~ % uname -a
Linux <hostname> 4.18.16-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 20 22:06:45 UTC 2018 x86_64 GNU/Linux
```
* Wesnoth:
```
 ~ % wesnoth --version                                                                                                                                                                   [139]
Battle for Wesnoth v1.14.5 (48bd45d7209-Clean)
Started on Tue Nov 13 15:41:36 2018

Battle for Wesnoth 1.14.5

Library versions:
Boost:             1.68
OpenSSL/libcrypto: 1.1.1   (runtime 1.1.1)
Cairo:             1.15.12 (runtime 1.16.0)
Pango:             1.42.3  (runtime 1.42.3)
SDL:               2.0.8   (runtime 2.0.9)
SDL_image:         2.0.3   (runtime 2.0.4)
SDL_mixer:         2.0.2   (runtime 2.0.4)
SDL_ttf:           2.0.14  (runtime 2.0.14)

Optional features:
Experimental OpenMP support:    yes
JPG screenshots:                yes
Lua console completion:         yes
Legacy bidirectional rendering: yes
D-Bus notifications back end:   yes
```
* Window manager:
```
 ~ % xmonad --version
xmonad 0.15
```
* Coredump information: https://gist.github.com/Phenitei/9d41e33c4c3ccf5c4af4411ab16cf44a

I will, of course, be happy to provide any additional information that may be required.
Thank you for your help!

**Comment by jostephd** [comment]
Is anything printed to stderr? Can you get a stack trace with debug symbols? Does it crash with `--userdata-dir` and `--userconfig-dir` pointing to new, empty directories? Do you have any add-ons installed via the package manager? And I'm taking a shot in the dark here, but try `--log-warning=all` as well.

I suppose it might be some incompatibility with libsdl 2.0.9, which is two weeks old.

**Comment by GregoryLundberg** [comment]
I run Arch, current this morning.
Cannot reproduce.
My thinking is this is probably an upstream issue with the Display Manager.

**Comment by Phenitei** [comment]
@GregoryLundberg: It is possible that this is related to my WM. I am talking to the devs there as well, and  we are also trying to figure it out. It has been established that someone with the same versions of Wesnoth and XMonad but SDL 2.0.3 does not appear have the problem; and the fullscreen should be making calls directly at Xorg anyway, bypassing the WM.

@jostephd :

 * This is printed to stderr:
```
 ~ % wesnoth -f
Battle for Wesnoth v1.14.5 (48bd45d7209-Clean)
Started on Wed Nov 14 14:38:36 2018


Data directory:               /usr/share/wesnoth
User configuration directory: /home/USER/.local/etc/wesnoth
User data directory:          /home/USER/.local/var/lib/wesnoth/1.14
Cache directory:              /home/USER/.local/var/cache/wesnoth

Setting mode to 958x1056
zsh: segmentation fault (core dumped)  wesnoth -f
```

* The backtrace with debug symbols (locally built with `DCMAKE_BUILD_TYPE=debug`) are [here](https://gist.github.com/Phenitei/54b655f888b94ec0a2cd3b554439a43c) for v1.15.0-dev and [here](https://gist.github.com/Phenitei/6d7c4549a4a3e2d529a819d01995ccbd) for v.1.14.5

 * Using a clean, new `userdata` and `userconfig` dir crashes as well, changing the screen resolution line from what is above to `Setting mode to 1280x720` (both are wrong, my screen is 1920x1080).

* Adding `--log-warning=all` does not produce any additional output.

The backstrace does indeed seem to suggest something with SDL... Should I try to build that as well with debugging symbols to get a more precise idea of what is wrong ?

**Comment by jostephd** [comment]
>     * Using a clean, new `userdata` and `userconfig` dir crashes as well, changing the screen resolution line from what is above to `Setting mode to 1280x720` (both are wrong, my screen is 1920x1080).

I have the same resolution and (with new userdata/userconfig dirs) get the same output, but the game loads fine and when I go to the "Display" tab in preferences, it says it's in 1920x1080.

Is there any point in asking @Phenitei to remove the cache directory? I can't think of how an invalid cache might cause a crash.

> The backstrace does indeed seem to suggest something with SDL... Should I try to build that as well with debugging symbols to get a more precise idea of what is wrong ?

Try using the same version of libsdl2 at build time and runtime. If that doesn't help, then yes, rebuild sdl with debug symbols, reproduce the bug in gdb and see which local variable can't be dereferenced.

Can anyone else see anything in @Phenitei's [backtrace](https://gist.github.com/Phenitei/6d7c4549a4a3e2d529a819d01995ccbd)? I don't but I don't know the gui2 code well.

**Comment by sevu** [comment]
> and the fullscreen should be making calls directly at Xorg anyway, bypassing the WM.

@Phenitei Wesnoth doesn't use true fullscreen anymore, it's a borderless window. E.g. one can switch workspaces while wesnoth is running, and it will stop playing the music if you do so… so I guess the WM is part of the equation.
There have been a few reports with exotic WMs during 1.13 development, IIRC they were mostly related to the WM making the windows smaller than allowed, but a few haven't been resolved.

You could try another of the slim WMs, like fluxbox or openbox.
Btw, the paths you gave above are quite nonstandard.

**Comment by Phenitei** [comment]
@sevu Thank you for the additional information! I haven't had enough time to spend on this to narrow down the issue yet, sadly. I would intuitively say that it is XMonad's tiling behavior that interacts wrongly with wesnoth (I have had no issues with openbox). As for the paths, if you are interested (the dicussion would be off topic), see [those dotfiles](https://github.com/ayekat/dotfiles).

**Comment by Wedge009** [comment]
It sounds like the problem lies somewhere outside of Wesnoth - but please remove the label if I'm wrong on that.

I have a recollection that this isn't the only time xmonad has been related to issues in Wesnoth but #1337 is the only one I could find (and that's rather old).

**Comment by jostephd** [comment]
@Wedge009 I don't think we know yet whether the cause of the bug is in xmonad or in wesnoth, do we? I know the problem doesn't occur under openbox but still. I think we should remove the label.

**Comment by jostephd** [comment]
Could you try this patch? It seems `SDL_DestroyRenderer` may not be called with a nullptr argument.

The first instance is definitely needed because the move constructor just above sets `renderer_` to nullptr. The second instance I'm not sure yet if it's needed or not.

```
diff --git a/src/gui/core/canvas.cpp b/src/gui/core/canvas.cpp
index 66365ce073b..4ff91d3f347 100644
--- a/src/gui/core/canvas.cpp
+++ b/src/gui/core/canvas.cpp
@@ -1381,7 +1381,8 @@ canvas::canvas(canvas&& c)
 
 canvas::~canvas()
 {
-	SDL_DestroyRenderer(renderer_);
+	if(renderer_)
+		SDL_DestroyRenderer(renderer_);
 }
 
 void canvas::draw(const bool force)
@@ -1406,7 +1407,8 @@ void canvas::draw(const bool force)
 		canvas_.assign(create_neutral_surface(w_, h_));
 	}
 
-	SDL_DestroyRenderer(renderer_);
+	if(renderer_)
+		SDL_DestroyRenderer(renderer_);
 
 	renderer_ = SDL_CreateSoftwareRenderer(canvas_);
 	SDL_SetRenderDrawBlendMode(renderer_, SDL_BLENDMODE_BLEND);
```

**Comment by Phenitei** [comment]
@jostephd Thank you for your answer. I have applied your patch and recompiled, and it does indeed fix the assertion failure. However, `wesnoth -f` still segfaults. The relevant backtrace is [here](https://gist.github.com/Phenitei/dc3e90ee4ffe571a2067dff66bed7604). The argument passed to the offending function doesn't appear to be null, and the SDL source code doesn't appear to explicit any preconditions except that, so I'm guessing that it may, in fact, be an upstream bug ?

**Comment by jostephd** [comment]
Okay, I pushed the first hunk.

**Question**: Should I push the second hunk as well? Could `renderer_` be nullptr in canvas::draw?

@Phenitei Before we conclude it's an upstream bug, are you sure it's the backtrace of the right thread? It's similar to the previous backtrace, and that one didn't go through SDL_DestroyRenderer at all.

**Comment by jostephd** [comment]
Hmm, okay. There is no pointer dereference on [line 350](http://hg.libsdl.org/SDL/file/8feb5da6f2fb/src/video/SDL_blit_A.c#l350) but there is one on line 351. I assume it is `srcp` that fails to be dereferenced? Is it NULL, or?

I don't know our SDL interfacing code well enough to either confirm or rule out the possibility of an upstream bug.

**Comment by Phenitei** [comment]
Hi @Wedge009, school interefered and I haven't played in some time. I just tested again, and still have the same problem:

```
 ~ % wesnoth -f                                                                                
Battle for Wesnoth v1.14.7
Started on Fri Sep 13 09:08:26 2019


Data directory:               /usr/share/wesnoth
User configuration directory: /home/USER/.local/etc/wesnoth
User data directory:          /home/USER/.local/var/lib/wesnoth/1.14
Cache directory:              /home/USER/.local/var/cache/wesnoth

Setting mode to 1920x1058
Checking lua scripts... ok
zsh: segmentation fault (core dumped)  wesnoth -f
```

```
 ~ % wesnoth --version
Battle for Wesnoth v1.14.7
Started on Fri Sep 13 09:10:26 2019

Battle for Wesnoth 1.14.7

Library versions:
Boost:             1.69
OpenSSL/libcrypto: 1.1.1c (runtime 1.1.1d)
Cairo:             1.17.3 (runtime 1.17.3)
Pango:             1.44.6 (runtime 1.44.6)
SDL:               2.0.10 (runtime 2.0.10)
SDL_image:         2.0.5  (runtime 2.0.5)
SDL_mixer:         2.0.4  (runtime 2.0.4)
SDL_ttf:           2.0.15 (runtime 2.0.15)

Optional features:
Experimental OpenMP support:    yes
JPG screenshots:                yes
Lua console completion:         yes
Legacy bidirectional rendering: yes
D-Bus notifications back end:   yes
```

I'll be happy to run any tests or patches you can think of, but I'm afraid I won't have anytime to do the bug hunting myself, sorry :/

**Comment by Wedge009** [comment]
No worries, it's good that you still responded. As best as I can tell we're kinda stuck - we can't really tell if it's a problem within Wesnoth itself or your particular set-up. That being said, I do remember a time when I couldn't run Wesnoth in full-screen on Linux, only windowed. But I don't have the problem now - and I use KDE not xmonad.

**Comment by AI0867** [comment]
Well, looks to me like (the way we use) SDL2 doesn't like xmonad's tiling forcing it into less-than-fullscreen.
Not sure if SDL actually supports this, but the current misbehaviour causing crashes is probably wesnoth's fault.

**Comment by mmavova** [comment]
I get the same crash in Openbox.

https://forums.wesnoth.org/viewtopic.php?f=4&t=54435&p=665622#p665622

**Comment by Wedge009** [comment]
Marking as confirmed with mmavova's input. Seems like it only happens with certain desktop environments?

**Comment by Wedge009** [comment]
For those who experienced this, if you're able to try 1.17.5+dev, I'd be interested to see if it still occurs with the new draw manager that's just been implemented. If not, you can wait till 1.17.6 is released.

**Comment by Wedge009** [comment]
Any update with any recently-released 1.17.x packages?

**Comment by mmavova** [comment]
I tested it with i3 WM just now, and it did not crash. Could not test with Openbox. Let's what other people say who reported this bug. 

A lot of libs/drivers on my system got updated though b/c Debian Stable got an update recently.

**Comment by Wedge009** [comment]
No further reports. Maybe close by the time 1.18 is released?
