### ISSUE TITLE
[macOS] Thin unreadable font issue with new versions of pango

### ISSUE THREAD

**Issue by hrubymar10** [wesnoth/wesnoth#5099]
This issue replaces old already closed issue #2859 which contains old informations.

### Game and System Information
* This issue is reproducible since Wesnoth 1.15.4 where was new pango library used.
* Affected systems are OS X 10.11 - macOS 10.15.6 (all supported macOS)
* For some reason this issue **is NOT** reproducible in macOS 11 Big Sure beta
* Issue is not language specific

### Screenshots
> OS X 10.11.6 (15G22010) El Capitan
![image](https://user-images.githubusercontent.com/2218817/91037645-a83ebf00-e609-11ea-8482-6db8c35d791c.png)

> macOS 11 (20A5354i) Big Sure Beta 5
![image](https://user-images.githubusercontent.com/2218817/91038865-cc030480-e60b-11ea-865a-091cb9b604de.png)

### Describe the bug
As you can see from attached screenshots, font used in wesnoth is thin and sometimes nearly unreadable. It is probably upstream issue in Pango but they doesn't look like they want to solve it anytime soon. They had this issue reported since April 2018. From previous issue I found that it worked with Pango 1.40.1 when Pango 1.46.1 is current stable. I was even able to track the commit which broke it https://github.com/GNOME/pango/commit/fcec6f721d5254b9010814023f98f541ca798b02 . It wasn't blocker issue before but it is now, because it is now impossible to build new libraries with old version of Pango and because of new Apple Silicon support (#4967) on which I am working I need the latest versions of all libraries. Also I have to mention that from previous issue it was broken by using new fonts which was added to wesnoth in this commit https://github.com/wesnoth/wesnoth/commit/2e81aed96d9d524ead5efc01900bae317901107d .

**Comment by Pentarctagon** [comment]
So without the fonts added in that commit, the issue doesn't happen?

**Comment by hrubymar10** [comment]
@Pentarctagon Yes. When I remove all fonts added in that commit, it seems to work fine
![image](https://user-images.githubusercontent.com/2218817/91176764-08556400-e6e3-11ea-9c73-71b6ab0f2a67.png)

IIRC I had to remove just `Lato-Thin.ttf` and it's italic version to make it work, but I should test it first

**Comment by Pentarctagon** [comment]
@Vultraz given the commit message starts with "Might as well have the whole bunch", are those fonts actually needed by Wesnoth?

**Comment by hrubymar10** [comment]
@Vultraz ^^ ?

@Pentarctagon everything worked fine during basic testing but I could miss something...

**Comment by mschoeck-zz** [comment]
I just tested it, and at least on my build it's the two Lato-Hairline fonts that cause the issue, not Lato-Thin.

**Comment by mattsc** [comment]
I just tested it, and at least on my build it's the two Lato-Hairline fonts that cause the issue, not Lato-Thin

**Comment by Pentarctagon** [comment]
Closed in #5107

**Comment by gfgtdf** [comment]
This is still an updateam bug right? Did you file an upstream bugreport ?

**Comment by Pentarctagon** [comment]
https://github.com/wesnoth/wesnoth/issues/2859#issuecomment-380710558 and the next comment.

**Comment by gfgtdf** [comment]
Okay wait, so this is fixed in pango 1.46.1 as said in the first post, then why is this a problem? Dont we have control over the pngo version we use on macosx like on windows?

> It wasn't blocker issue before but it is now, because it is now impossible to build new libraries with old version of Pango and because

You say you cannot use older version of pango but why can't you use newer versions ?

**Comment by Pentarctagon** [comment]
It isn't fixed on 1.46.1 - 1.46.1 is just the current stable version of pango.

**Comment by gfgtdf** [comment]
Ok misread the first post, but here https://gitlab.gnome.org/GNOME/pango/-/issues/307#note_879439  @hrubymar10  says he can no longer rproduce it

**Comment by hrubymar10** [comment]
Wesnoth 1.15.4 uses pango 1.45.3
Current MacCompileStuff provides and next wesnoth package will probably use pango 1.46.1

Every pango since version 1.40.1 is broken on every supported stable macOS version (OS X 10.11 - macOS 10.15.6)

For some reason I cannot reproduce this issue on current beta version of next stable macOS (macOS 11.0).

I closed the issue on pango’s bug tracker because I thought that it was fixed but it wasn’t. It just for some reason works on macOS 11 beta.

I am planning to reopen this pango’s issue but I haven’t done it yet.
