### ISSUE TITLE
Segfault with lua 

### ISSUE THREAD

**Issue by rubyFeedback** [wesnoth/wesnoth#5751]
Bug:

20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Kobold.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Razorbird.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Stone Golem.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Sylph.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Thunderbird.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Tidal.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Undine.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Wisp.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Zephyr.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Brazier Imp.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Ethereal Orb.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Fire Wisp.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Furnace Beast.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Ice Crab.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Kobold.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Razorbird.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Stone Golem.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Sylph.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Thunderbird.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Tidal.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Undine.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Wisp.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Zephyr.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Brazier Imp.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Ethereal Orb.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Fire Wisp.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Furnace Beast.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Ice Crab.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Kobold.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Razorbird.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Stone Golem.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Sylph.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Thunderbird.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Tidal.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Undine.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Wisp.
20210429 18:52:41 error ai/recruitment: Couldn't find unit type: Zephyr.
Invalid WML found: Unit-type "Brazier Imp" doesn't exist.
Invalid WML found: Unit-type "Ethereal Orb" doesn't exist.
Invalid WML found: Unit-type "Fire Wisp" doesn't exist.
Invalid WML found: Unit-type "Furnace Beast" doesn't exist.
Invalid WML found: Unit-type "Ice Crab" doesn't exist.
Invalid WML found: Unit-type "Kobold" doesn't exist.
Invalid WML found: Unit-type "Razorbird" doesn't exist.
Invalid WML found: Unit-type "Stone Golem" doesn't exist.
Invalid WML found: Unit-type "Sylph" doesn't exist.
Invalid WML found: Unit-type "Thunderbird" doesn't exist.
Invalid WML found: Unit-type "Tidal" doesn't exist.
Invalid WML found: Unit-type "Undine" doesn't exist.
Invalid WML found: Unit-type "Wisp" doesn't exist.
Invalid WML found: Unit-type "Zephyr" doesn't exist.
20210429 18:53:29 error scripting/lua: game_error: unknown unit type: Orcish Raider
stack traceback:
        [C]: in local 'cmd'
        lua/wml-utils.lua:144: in field 'handle_event_commands'
        lua/wml-flow.lua:5: in function <lua/wml-flow.lua:4>
Segmentation fault

I forgot the name of the campaign; something with a forest, vampires and fog.

It may be that the campaign is faulty, but I don't think such a segfault should
be possible. I never had wesnoth crash like this. Would be nice if lua-related
errors could be "sandboxed" and caught. 

This is an add-on, so it is probably the fault of that add-on but even then 
the wesnoth engine should not crash like this IMO.

By the way, perhaps the campaign strictness could be increased as well, 
so that things such as "20210429 18:52:41 error ai/recruitment: Couldn't
find unit type: Kobold." could not happen either. Or perhaps separate
add-ons in stable, and dev-mode or something.

**Comment by Pentarctagon** [comment]
The name of the campaign is really needed here, preferably also you could upload a save file from right before this happens.

**Comment by knyghtmare** [comment]
> I forgot the name of the campaign; something with a forest, vampires and fog.

This is mine. Let me see if I can get a fix out tonight.

**Comment by CelticMinstrel** [comment]
> Also, why here and not on the campaign's own repo or forums?

Because it's a segfault. No matter what a campaign does wrong, the game should never segfault.

**Comment by Pentarctagon** [comment]
@knyghtmare The unit types not being found should ideally be reported to you.  Wesnoth crashing though means there's also a bug somewhere in Wesnoth's own C++ code.

**Comment by knyghtmare** [comment]
> @knyghtmare The unit types not being found should ideally be reported to you. Wesnoth crashing though means there's also a bug somewhere in Wesnoth's own C++ code. But like I said, without any information on how to reproduce the issue, it's hard to know what's actually going wrong.

I updated my add-ons and this warnings have been resolved. However, I am not sure how this even segfaulted and the scenario loaded just fine for me.

**Comment by Wedge009** [comment]
It's been a month since the last comment - has this been resolved? Could it be closed?

**Comment by Pentarctagon** [comment]
It's not resolved, but I suppose it may as well be closed given the lack of information.
