### ISSUE TITLE
Incorrect standing animation WML causes Wesnoth to crash

### ISSUE THREAD

**Issue by Toranks** [wesnoth/wesnoth#7190]
### Game and System Information

The Battle for Wesnoth version 1.17.10 x86_64
Running on Microsoft Windows 7 Service Pack 1 (6.1.7601) x86_64
Distribution channel: Steam

Game paths
==========

Data dir:        D:\SteamLibrary\steamapps\common\wesnoth
User config dir: C:\Users\USER\Documents\My Games\Wesnoth1.17
User data dir:   C:\Users\USER\Documents\My Games\Wesnoth1.17
Saves dir:       C:\Users\USER\Documents\My Games\Wesnoth1.17\saves
Add-ons dir:     C:\Users\USER\Documents\My Games\Wesnoth1.17\data\add-ons
Cache dir:       C:\Users\USER\Documents\My Games\Wesnoth1.17\cache
Logs dir:        C:\Users\USER\Documents\My Games\Wesnoth1.17\logs

Libraries
=========

Boost:             1.80
Lua:               5.4.4
OpenSSL/libcrypto: 1.1.1s (runtime 1.1.1s)
Cairo:             1.17.6 (runtime 1.17.6)
Pango:             1.50.11 (runtime 1.50.11)
SDL:               2.24.1 (runtime 2.24.1)
SDL_image:         2.6.2 (runtime 2.6.2)
SDL_mixer:         2.6.2 (runtime 2.6.2)

Features
========

Lua console completion:       yes
Win32 notifications back end: yes

Current video settings
======================

SDL video drivers:        [windows] dummy
Window size:              1920x1080
Game canvas size:         1920x1080
Final render target size: 1920x1080
Screen refresh rate:      60

Current audio settings
======================

SDL audio drivers:  [wasapi] directsound
Number of channels: 2
Output rate:        48000 Hz
Sample format:      signed 16 bit little-endian
Sample size:        4096 bytes

Installed add-ons
=================

A_New_Order:                  1.4.1
Advance_Wesnoth_Wars_fork:    1.17.7
Akladian_Music:               1.0.1
An_Orcish_Incursion:          1.0.3
Eastern_Invasion_Dalas:       1.1.4
Era_of_Magic:                 3.9.5
Era_of_Magic_Resources:       1.8.0
Gui_Debug_Tools:              0.10.2
Non_Fatal_Wounds_Extended:    1.1
To_Lands_Unknown:             3.6.0
To_Lands_Unknown_Resources_1: 2.0.0
To_Lands_Unknown_Resources_2: 1.7.1

### Description of the bug

The game crashes without a clear log, reports are about some seconds ago, not related with the crash:
[wesnoth-20221204-042212-1927577251.log](https://github.com/wesnoth/wesnoth/files/10147813/wesnoth-20221204-042212-1927577251.log)
[wesnoth-20221204-042003-1548564325.log](https://github.com/wesnoth/wesnoth/files/10147814/wesnoth-20221204-042003-1548564325.log)
[wesnoth-20221204-041926-3557225143.log](https://github.com/wesnoth/wesnoth/files/10147815/wesnoth-20221204-041926-3557225143.log)

### Steps to reproduce the behavior

1. Create a bat with debug and change his side to a enemy
2. Create one or more walking corpses, attack the bat, and transform on a walking dead bat
3. Skip a turn and move the walking dead bat to S, SE or SW and see that moves correctly. So move to N, NW or NE
4. APPCRASH

### Additional context

Although I have several addons installed, in the tests I do not have them active. I don't think they are related. Other walking dead (I haven't tried all of them) work fine.
Here I leave a savegame ready to move the bat and generate the crash.
[2 jug.zip](https://github.com/wesnoth/wesnoth/files/10147820/2.jug.zip)

**Comment by Pentarctagon** [comment]
Backtrace:
```
#0  0x0000555555b673c6 in std::__shared_ptr<unit const, (__gnu_cxx::_Lock_policy)2>::get() const (this=0x0) at /usr/include/c++/11/bits/shared_ptr_base.h:1296
#1  0x0000555555b64e34 in std::__shared_ptr_access<unit const, (__gnu_cxx::_Lock_policy)2, false, false>::_M_get() const (this=0x0) at /usr/include/c++/11/bits/shared_ptr_base.h:993
#2  0x0000555555b62644 in std::__shared_ptr_access<unit const, (__gnu_cxx::_Lock_policy)2, false, false>::operator->() const (this=0x0) at /usr/include/c++/11/bits/shared_ptr_base.h:987
#3  0x0000555556044f25 in unit_animator::get_animation_time_potential() const (this=0x7fffffff9cf0) at src/units/animation.cpp:1482
#4  0x00005555560e0bd2 in unit_display::(anonymous namespace)::move_unit_between(map_location const&, map_location const&, unit_ptr, unsigned int, unsigned int, unit_animator&, display&)
     (a=..., b=..., temp_unit=std::shared_ptr<unit> (use count 2, weak count 1) = {...}, step_num=0, step_left=0, animator=..., disp=...) at src/units/udisplay.cpp:157
#5  0x00005555560e1f34 in unit_display::unit_mover::proceed_to(std::shared_ptr<unit>, unsigned long, bool, bool) (this=0x7fffffff9ce0, u=std::shared_ptr<unit> (use count 4, weak count 1) = {...}, path_index=1, update=true, wait=false) at src/units/udisplay.cpp:372
#6  0x00005555562052bd in actions::(anonymous namespace)::unit_mover::do_move(actions::(anonymous namespace)::unit_mover::route_iterator const&, actions::(anonymous namespace)::unit_mover::route_iterator const&, unit_display::unit_mover&)
   (this=0x7fffffffa210, step_from={x = 41, y = 20}, step_to={x = 41, y = 19}, animator=...) at src/actions/move.cpp:533
#7  0x00005555562070a6 in actions::(anonymous namespace)::unit_mover::try_actual_movement(bool) (this=0x7fffffffa210, show=true) at src/actions/move.cpp:974
#8  0x00005555562089c3 in actions::move_unit_internal(actions::undo_list*, bool, bool*, actions::(anonymous namespace)::unit_mover&) (undo_stack=0x5555598f22c0, show_move=true, interrupted=0x7fffffffa677, mover=...) at src/actions/move.cpp:1177
#9  0x00005555562095d3 in actions::move_unit_and_record(std::vector<map_location, std::allocator<map_location> > const&, actions::undo_list*, bool, bool, bool*, actions::move_unit_spectator*)
    (steps=std::vector of length 2, capacity 2 = {...}, undo_stack=0x5555598f22c0, continued_move=false, show_move=true, interrupted=0x7fffffffa677, move_spectator=0x0) at src/actions/move.cpp:1261
#10 0x00005555565b4261 in events::mouse_handler::move_unit_along_route(std::vector<map_location, std::allocator<map_location> > const&, bool&) (this=0x7fffffffc148, steps=std::vector of length 2, capacity 2 = {...}, interrupted=@0x7fffffffa677: false) at src/mouse_events.cpp:1184
#11 0x00005555565b3cc2 in events::mouse_handler::move_unit_along_current_route() (this=0x7fffffffc148) at src/mouse_events.cpp:1129
#12 0x00005555565b2921 in events::mouse_handler::move_action(bool) (this=0x7fffffffc148, browse=false) at src/mouse_events.cpp:989
#13 0x00005555565b1bec in events::mouse_handler::select_or_action(bool) (this=0x7fffffffc148, browse=false) at src/mouse_events.cpp:808
#14 0x000055555657d178 in play_controller::hotkey_handler::select_and_action() (this=0x5555583f67c0) at src/hotkey/hotkey_handler.cpp:123
#15 0x0000555556a78561 in hotkey::command_executor::do_execute_command(hotkey::hotkey_command const&, int, bool, bool) (this=0x5555583f67c0, cmd=..., press=true, release=false) at src/hotkey/command_executor.cpp:339
#16 0x000055555657dd0f in play_controller::hotkey_handler::do_execute_command(hotkey::hotkey_command const&, int, bool, bool) (this=0x5555583f67c0, cmd=..., index=-1, press=true, release=false) at src/hotkey/hotkey_handler.cpp:276
#17 0x0000555556a79f58 in hotkey::command_executor::execute_command_wrap(hotkey::command_executor::queued_command const&) (this=0x5555583f67c0, command=...) at src/hotkey/command_executor.cpp:622
#18 0x0000555556a7ac3a in hotkey::command_executor::run_queued_commands() (this=0x5555583f67c0) at src/hotkey/command_executor.cpp:762
#19 0x0000555556a79854 in hotkey::run_events(hotkey::command_executor*) (executor=0x5555583f67c0) at src/hotkey/command_executor.cpp:577
#20 0x0000555556a7977b in hotkey::mbutton_event(SDL_Event const&, hotkey::command_executor*) (event=..., executor=0x5555583f67c0) at src/hotkey/command_executor.cpp:549
#21 0x000055555635b90d in controller_base::handle_event(SDL_Event const&) (this=0x7fffffffbff0, event=...) at src/controller_base.cpp:191
#22 0x0000555556a53b97 in events::pump() () at src/events.cpp:723
#23 0x000055555635c548 in controller_base::play_slice(bool) (this=0x7fffffffbff0, is_delay_enabled=true) at src/controller_base.cpp:392
#24 0x0000555555e6d359 in playmp_controller::play_slice(bool) (this=0x7fffffffbff0, is_delay_enabled=true) at src/playmp_controller.cpp:492
#25 0x0000555555e5e660 in play_controller::play_slice_catch() (this=0x7fffffffbff0) at src/play_controller.cpp:1155
#26 0x0000555555e6a922 in playmp_controller::play_human_turn() (this=0x7fffffffbff0) at src/playmp_controller.cpp:158
#27 0x0000555555e736e6 in playsingle_controller::play_side_impl() (this=0x7fffffffbff0) at src/playsingle_controller.cpp:429
#28 0x0000555555e5ffc2 in play_controller::play_side() (this=0x7fffffffbff0) at src/play_controller.cpp:1329
#29 0x0000555555e60400 in play_controller::play_turn() (this=0x7fffffffbff0) at src/play_controller.cpp:1369
#30 0x0000555555e718a0 in playsingle_controller::play_scenario_main_loop() (this=0x7fffffffbff0) at src/playsingle_controller.cpp:178
#31 0x0000555555e722e5 in playsingle_controller::play_scenario(config const&) (this=0x7fffffffbff0, level=...) at src/playsingle_controller.cpp:284
#32 0x0000555555b89d1b in campaign_controller::playmp_scenario(end_level_data&) (this=0x7fffffffc8e0, end_level=...) at src/game_initialization/playcampaign.cpp:223
#33 0x0000555555b89ff9 in campaign_controller::play_game() (this=0x7fffffffc8e0) at src/game_initialization/playcampaign.cpp:286
#34 0x0000555555b9522d in game_launcher::launch_game(game_launcher::reload_mode) (this=0x5555577e62d0, reload=game_launcher::reload_mode::RELOAD_DATA) at src/game_launcher.cpp:1021
#35 0x00005555559d88af in do_gameloop(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) (args=std::vector of length 2, capacity 2 = {...}) at src/wesnoth.cpp:963
#36 0x00005555559d958e in main(int, char**) (argc=2, argv=0x7fffffffe628) at src/wesnoth.cpp:1147
```
Seems to be a segfault at https://github.com/wesnoth/wesnoth/blob/e3bf0ec1c3137ca4556c205e433724d359accf1a/src/units/animation.cpp#L1482 due to `animated_units_` being empty.

**Comment by Pentarctagon** [comment]
@doofus-01 is there anything different about how the walking corpse's bat variation's animations are setup? I don't see the variation as having any movement animation defined, either for north or south.

**Comment by knyghtmare** [comment]
So, this is caused by #7102

**Comment by doofus-01** [comment]
It's fixed in #7167.  
It looks like I missed a few variations when testing the standing animations.

**Comment by knyghtmare** [comment]
Has the fix in 1.17.11 been tested? So it can be closed?

**Comment by CelticMinstrel** [comment]
#7167 does not fix this issue. It could still happen if you were to construct an ill-formed unit definition. So this should be left open until the actual issue is fixed.

**Comment by doofus-01** [comment]
7167 solves the specific problem with the dead bat, doesn't it?  If you don't want to close this because of some remaining underlying issue, it would be good to change the title to something more on point.  (I only have the vaguest understanding of the issue, so I won't change it myself.)

**Comment by stevecotton** [comment]
Duplicate of #5032. Not sure which one to close - this one has a savegame attached, but it also has discussion about the zombies.

**Comment by Pentarctagon** [comment]
I'd say this one should be closed.
