### ISSUE TITLE
[Map Editor] Add Option "Replace Unknown Terrains" with `Gg` to Load maps

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#7389]
### Describe the desired feature

Suppose if there is a map which comes from 1.10-1.13 and someone wishes to open it to see if it's worth extracting. However, the addon itself depended on an external terrain pack which might be available or mentioned in the addons. Thus, I propose some option in the "Unknown Terrain Found:" dialog which would prompt player/map-maker if they wish to load the map, with unknown terrains replaced with the default `Gg` terrain. That way, the large and huge maps from previous servers can be opened (by a mass search and replace performed by the engine).

**Comment by CelticMinstrel** [comment]
Even better, allow the user to choose to replace it with any terrain they wish.

**Comment by stevecotton** [comment]
It should have different handling for unknown base terrains vs unknown overlays (and would need to handle both).

> Even better, allow the user to choose to replace it with any terrain they wish.

Having a short list to select from sounds like it would be almost as good but possibly easier to implement - maybe just `Gg` and `Xv`.

**Comment by CelticMinstrel** [comment]
Another possibility is for it to, instead of complaining about an unknown terrain, _automatically add it to the terrain list as a hidden terrain_. Then you can still see the original terrain code when editing the map to replace them.

**Comment by doofus-01** [comment]
During the load-game dialog, the minimap fails to display whenever there is a non-core terrain (unless that's been fixed in the last month or two).  It seems like there could be a common solution to that and to the editor loading issue.  Would/Could the requested fix also address the load-game minimap?

**Comment by CelticMinstrel** [comment]
I guess at best it could make the minimap display with unknown terrains replaced by grass, which is still wrong but at least less wrong.
