### ISSUE TITLE
`--log-none=deprecation` doesn't override a previous `--debug` flag on the command line

### ISSUE THREAD

**Issue by cooljeanius** [wesnoth/wesnoth#7894]
### Game and System Information

- **Version:** 1.16.10
- **Downloaded from:** Steam
- **OS:** macOS Big Sur

### Description of the bug

As described on Discord/IRC, I have tried starting Wesnoth with both the `--debug` and `--log-none=deprecation` flags, and still get spammed with deprecation messages, even though I have requested not to see them.

### Steps to reproduce the behavior

1. Start Wesnoth from the command line with both the `--debug` and `--log-none=deprecation` flags
2. Observe console output

### Expected behavior

`--log-none=deprecation` should override a previous `--debug` flag.

**Comment by ZBugH1** [comment]
Confirmed on my end. I'll take a look when I get some free time later this week

**Comment by OmarElfouly** [comment]
Hello :)
I just wanted to confirm this issue has been resolved in #8076 
(p.s. Im new to contributing and on the hunt for my first issue so you might see me elsewhere in the repo )

**Comment by soliton-** [comment]
This issue is not resolved. One general problem is that our command line handling mostly doesn't care for the given argument order.

**Comment by OmarElfouly** [comment]
> This issue is not resolved. One general problem is that our command line handling mostly doesn't care for the given argument order.

Oh that's interesting. Does that mean that the output of `--debug --log-none=deprecation` should be different than  `--log-none=deprecation --debug`

**Comment by soliton-** [comment]
That is what this issue is about, yes.

**Comment by gfgtdf** [comment]
> That is what this issue is about, yes.

i strongly disagree here, explicitly specifying  --log-none=deprecatio should always overrride --debug, unrelated to the other in that they appear.

**Comment by OmarElfouly** [comment]
> i strongly disagree here, explicitly specifying --log-none=deprecatio should always overrride --debug, unrelated to the other in that they appear.

I agree with this. My initial understanding is that the issue was about --log-none=deprecation being ignored when --debug is passed which should not happen no matter the order.

**Comment by soliton-** [comment]
> i strongly disagree here, explicitly specifying --log-none=deprecatio should always overrride --debug, unrelated to the other in that they appear.

Well, I strongly disagree that argument order should not matter. Our command line handling is pretty annoying in that it does not most of the time.

The other issue is how --debug works though. Perhaps you assume --debug just overwrites the log setting but it changes the severity relative to what it is at the time and also sets it back if you disable debug again at runtime. Whether that is a good idea or not is a different question.

**Comment by OmarElfouly** [comment]
Okay  thank you @soliton- , that clears some things up but what I don't understand is how the order of the arguments will have a difference, unless what you were referring to is how the order of passing it during runtime will cause different behavior?

Like I would appreciate it if you described the expected behavior of both --debug --log-none=deprecation  and  --log-none=deprecation --debug

Whatever the case though, I worry that any work done to allow for a workaround will only force more workarounds later due to the way debug is implemented. Would it make more sense to change the way debug works instead?

**Comment by soliton-** [comment]
> Like I would appreciate it if you described the expected behavior of both --debug --log-none=deprecation and --log-none=deprecation --debug

--debug increases severity by 2 and --log-none=deprecation sets severity to none. So if --debug is first --log-none=deprecation simply overwrites. The other way around first severity is set to none and then --debug increases it to warning.

> Whatever the case though, I worry that any work done to allow for a workaround will only force more workarounds later due to the way debug is implemented. Would it make more sense to change the way debug works instead?

There is no workaround requested as far as I can tell. The effects of the command line arguments should just be applied in the order they are specified.

If you want to propose different behavior for --debug then go ahead and propose something. My assumption is that the current behavior is meant to show deprecation notices only in debug mode.
