### ISSUE TITLE
[filter_ability] oddity when type_value is empty

### ISSUE THREAD

**Issue by soliton-** [wesnoth/wesnoth#7944]
https://github.com/wesnoth/wesnoth/blob/627244b0fde9301ff88283185bba4e161bacb518/src/units/unit.cpp#L1424-L1444

This function returns true early if `type_value` is empty but if there is an empty value in a comma separated list it's used anyway. Also the schema seems to suggest an empty value is valid.

I think the goal is to support checking for an ability with neither `value`, `add`, `sub`, `multiply` nor `divide`? If so the initial empty check should use `blank` or `has_attribute` instead. Otherwise empty values need to be removed or cause an error or something for lists as well.

Also this should be documented on the wiki.

**Comment by soliton-** [comment]
Looks like this was added in #7616 by @newfrenchy83.

**Comment by newfrenchy83** [comment]
oddity fixed in https://github.com/wesnoth/wesnoth/pull/7924/commits/eed6edc9bdbeadbddb6180fd6d968537279818aa

**Comment by soliton-** [comment]
@newfrenchy83 Write documentation for the attribute `type_value`.
I've explained how the function `type_value_if_present` is wrong. Your commit does not fix that. Just explain how it should work. Do not write any code. Use english words.

**Comment by newfrenchy83** [comment]
The purpose of value_type is to check which numeric attribute is used in an ability, if the filter is not present or is empty, it returns true by default, otherwise, you must first check if one of these attributes is present before comparing with the filter, the problem you raise is that I did not impose on the filter to only be able to take value, add tec as valuer, right? So I'm going to change that immediately.

If https://github.com/wesnoth/wesnoth/pull/7924#issuecomment-1751679935 is merged, then this filter will be obsolete and may be deprecated.

**Comment by CelticMinstrel** [comment]
My understanding was that `value_type` is meant to detect which of the add/sub/multiply/divide/value attributes are used. For example, if you want to match only multiplicative abilities, you can write `value_type=multiply`.

**Comment by newfrenchy83** [comment]
> My understanding was that `type_value` is meant to detect which of the add/sub/multiply/divide/value attributes are used. For example, if you want to match only multiplicative abilities, you can write `type_value=multiply`.
> 
> I don't see how that's obsoleted by #7924.

after bug fixed use multiply=0-4 will be same effect and limit matche to value between 0 and 4 without need of value_type, but if you don't want use a value range then value_type is not obsoleted

**Comment by newfrenchy83** [comment]
what https://github.com/wesnoth/wesnoth/pull/7924/commits/308f768636ac4925c4d7b04f5101a181e20f48ed is correct for you?

**Comment by soliton-** [comment]
Ok, so I missed that split silently removes empty values by default. So even after split there will be no empty values in the list. So it makes little sense that the function checks even if `cfg_type_value` is empty.

IMO it would make sense to support empty values to support checking for an ability with neither value, add, sub, multiply nor divide but it seems like that was not the goal.

I'm fine either way. I have no clue what use cases `type_value` is for anyway.

I will say though that using `empty()` everywhere when really you want to check if an attribute is present is constantly confusing. You're simply singling out one invalid value while keeping all other ones. So in this case `type_value=""` is as if you didn't specify `type_value` at all while `type_value="foo"` fails the check instead.

**Comment by newfrenchy83** [comment]
> Ok, so I missed that split silently removes empty values by default. So even after split there will be no empty values in the list. So it makes little sense that the function checks even if `cfg_type_value` is empty.
> 
> IMO it would make sense to support empty values to support checking for an ability with neither value, add, sub, multiply nor divide but it seems like that was not the goal.
> 
> I'm fine either way. I have no clue what use cases `type_value` is for anyway.
> 
> I will say though that using `empty()` everywhere when really you want to check if an attribute is present is constantly confusing. You're simply singling out one invalid value while keeping all other ones. So in this case `type_value=""` is as if you didn't specify `type_value` at all while `type_value="foo"` fails the check instead.

for me  `type_value=""` is same what if type_value did'nt specified then yes use empty() is more indicated for me

**Comment by stevecotton** [comment]
> My understanding was that `type_value` is meant to detect which of the add/sub/multiply/divide/value attributes are used. For example, if you want to match only multiplicative abilities, you can write `type_value=multiply`.

I think that's the right understanding, but now that @soliton- has asked the question, I'm wondering if there is any reason to have `type_value` instead of just filtering for the desired effect. For example, if we want to look for big damage boosts, then we could filter for `add=5-infinity` `[or]` `multiply=1.5-infinity`.

@newfrenchy83 please would you give an example of an ability or UMC event that would need to use `type_value` instead of checking for a suitably large `add=` or `multiply=`?

**Comment by newfrenchy83** [comment]
> > My understanding was that `type_value` is meant to detect which of the add/sub/multiply/divide/value attributes are used. For example, if you want to match only multiplicative abilities, you can write `type_value=multiply`.
> 
> I think that's the right understanding, but now that @soliton- has asked the question, I'm wondering if there is any reason to have `type_value` instead of just filtering for the desired effect. For example, if we want to look for big damage boosts, then we could filter for `add=5-infinity` `[or]` `multiply=1.5-infinity`.
> 
> @newfrenchy83 please would you give an example of an ability or UMC event that would need to use `type_value` instead of checking for a suitably large `add=` or `multiply=`?

No, i don't have exemple to give, because after bug repairing check multiply=1-infinity  exclude all abilitie who don't use multiply.

**Comment by newfrenchy83** [comment]
> > for me `type_value=""` is same what if type_value did'nt specified then yes use empty() is more indicated for me
> 
> How in the world is an empty value the same as not giving a value? Why would you not allow an attribute with an empty value? In general an attribute can have any value. Certainly there may be cases where an empty value is not desirable or invalid or whatever but pretending it is not there is just confusing. Similarly confusing is just checking for empty as an invalid value and accepting all other invalid values and just not do anything useful.

in this case value_type cannot check what value, add, sub, multiply or divide, whether value_type is empty or absent is equivalent to an incorrect value, value_type="true" for example

**Comment by stevecotton** [comment]
> > please would you give an example of an ability or UMC event that would need to use `type_value` instead of checking for a suitably large `add=` or `multiply=`?
> 
> No, i don't have exemple to give, because after bug repairing check multiply=1-infinity exclude all abilitie who don't use multiply.

Then what do we lose by simply removing `type_value` from the filter, at least for 1.18's API?

**Comment by soliton-** [comment]
> in this case value_type cannot check what value, add, sub, multiply or divide, whether value_type is empty or absent is equivalent to an incorrect value, value_type="true" for example

It'd be weird if absent would be equivalent to an invalid value. But certainly empty and invalid would make sense to be equivalent yet neither are. When `type_value` is absent or empty there is an early return with true yet any other invalid value is checked against `cfg_type_value` which will never contain an incorrect value (except confusingly empty which is why I thought that was a valid value). Thus `type_value=""` will always match while `type_value="true"` will always fail to match.
