### ISSUE TITLE
GUI2 Help

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#9417]
### Game and System Information

- **Version:** GUI2 Help was introduced after 1.19.4, in #3653.
- **OS:** N/A

### Description of the bug

I suppose it's better to report as a new issue than continue the conversation in #3653 which is now merged. I didn't even realise it had been merged till now. @white-haired-uncle has already reported some issues in that PR, post-merge.

I think shrinking the Help window doesn't help especially where images are already over-sized after scaling.
![image](https://github.com/user-attachments/assets/7d2585e2-5510-4ee7-9f1e-537d5e8ed44b)

In that example, there may be an issue with translations because I'm pretty sure `text='` shouldn't be there.

There's also weird resizing caused by ee82b0ec10ed97f9824ad9f3f6079f315e99f4f2 specifically.
![image](https://github.com/user-attachments/assets/a4243203-be94-43e5-9005-733fda69d208)

### Steps to reproduce the behavior

View Help via main menu or in-game unit description.

### Expected behavior

Example from 1.19.4 release where GUI1 was still used.
![image](https://github.com/user-attachments/assets/5272bdac-17db-4f02-adcb-7c626d9b378e)

**Comment by Wedge009** [comment]
The tree view on the left appears to be fixed width: https://github.com/wesnoth/wesnoth/issues/1826#issuecomment-2389183607

**Comment by babaissarkar** [comment]
Thanks for the detailed report.
1. Many of these are caused by the fact that Pixel Scaling support isn't correctly working inside the help browser and the unit topic generators. Further complicated by the fact that I have a low res monitor, so pixel scaling doesn't work for me. Vultraz has been working on that part.
2. The `text` is a leftover, will be removed.
3. Are you on latest commit (confirming)? I recently push a patch for the wrapping issue, so need to know if that fixed it (or not).

**Comment by Wedge009** [comment]
I was cleanly compiled at time of writing, confirming 4062f579e35.

Yes, I recognise scaling wasn't great for Help even before the conversion to GUI2 - I wasn't a fan of images being scaled as well. It's also compounded by the lack of an 'in between' scale between 1 and 2 (that's #8608).

I had a feeling this was actively being worked on still but again, still thought it best to record in an issue. By no means is this meant to detract from your and others' hard work on this.

**Comment by babaissarkar** [comment]
some screenshots from my side (8267bc3d167a7ca2b59abc27cb1b05622212ec14)
![Screenshot from 2024-10-02 22-43-39](https://github.com/user-attachments/assets/f2ea9254-46f6-4974-88b5-7bff923958b1)
![Screenshot from 2024-10-02 22-42-33](https://github.com/user-attachments/assets/a88035f6-8801-409e-87e3-ae6a1452dc1c)

**Comment by babaissarkar** [comment]
> I had a feeling this was actively being worked on still but again, still thought it best to record in an issue. By no means is this meant to detract from your and others' hard work on this.
The report is highly appreciated.

**Comment by babaissarkar** [comment]
looking once again, my guess it's the translation that contains the `text=`. the original doesn't contain that.

**Comment by babaissarkar** [comment]
@Wedge009 BTW, can you post the logs with `--log-domaing=gui/widget/rich_label` for the Dragoon case? Just go to Titlescreen -> Help -> Open the Dragoon page -> immediatly close help browser using  close button -> upload the generated logs here.

**Comment by Wedge009** [comment]
Edit: This is split out into #9986.

---

Possibly. Another thing that doesn't happen with English rendering is a huge gap after Attacks heading for the French Elvish Outrider:

![image](https://github.com/user-attachments/assets/b9faacbb-9223-49c3-a7c5-4c1ca87cb5a9)

I reset scaling to 1x for this example.

**Comment by babaissarkar** [comment]
need to check this, but most likely it's the markup syntax getting changed, so the translations need to be updated with new markup.

**Comment by Wedge009** [comment]
I should point out I'm not normally up at this hour (UTC+1000), I applied debug logging via Preferences since `--log-domain` wasn't recognised.

[wesnoth-20241003-032716-1817539422.log](https://github.com/user-attachments/files/17233879/wesnoth-20241003-032716-1817539422.log)

**Comment by CelticMinstrel** [comment]
> looking once again, my guess it's the translation that contains the `text=`. the original doesn't contain that.

However, that format is still considered valid by the parser, so unless the markup in the translation is actually invalid, you shouldn't see `text=` in the output…

**Comment by Wedge009** [comment]
I'm not sure what the mark-up in the translation is supposed to be doing but here's the relevant piece:
https://github.com/wesnoth/wesnoth/blob/4062f579e3508854e2d3624eb1079d6e8f70cca1/po/wesnoth-units/fr.po#L3700-L3768

**Comment by Wedge009** [comment]
I just noticed in @babaissarkar's images, the Outrider text demonstrates something I think white-haired-uncle already pointed out in that there's an expected line break in 'journey to a distant... land.'

**Comment by CelticMinstrel** [comment]
I don't see any actual issue in the French text there. It contains non-typographic apostrophes in the italics tag, but they're properly escaped with a backslash. I suspect there's probably a bug in the parser – perhaps it's choking on the newlines in the attribute value?

**Comment by babaissarkar** [comment]
> I applied debug logging via Preferences since `--log-domain` wasn't recognised.

Sorry, my mistake, should be `--log-debug=gui/widget/rich_label`. See the manpages or `wesnoth --help`.

Managed to reproduce the `text=` issue:
![Screenshot from 2024-10-03 07-03-26](https://github.com/user-attachments/assets/59ab7369-7c57-4921-88a7-d6f70c67061b)

Logs show that the `text=` is in parser output, but still need to investigate why it's coming there in the first place.

```
[italic]
	[text]
		text = text='Il était une fois un elfe du nom de Beirand, qui entreprit un voyage vers une terre lointaine.
Il chevaucha pendant treize jours, sans prendre de repos, jusqu'à ce qu'il entre dans la demeure d'une nymphe, au bord d'un lac.
« Regarde là-bas, Narya ! cria-t-il avec joie. Vois-tu ce fameux pommier au loin ? »
Sa monture répondit par un hennissement, sauta de joie, puis partit au galop.
Il ne fallut pas attendre un instant pour qu'une rafale souffle tout autour et qu'une voix aérienne se fasse entendre :
« Attends, elfe, ce bosquet est à moi. Je ne te donnerai aucun fruit, ni à toi ni à ton cheval. »
Ce à quoi il répondit : « S'il te plaît, accorde-nous un répit. Nous avons longtemps voyagé, vois-tu comme nous sommes las ? »
« De la fatigue, je perçois, elle est la vôtre, mais pour gagner ma grâce, disputons une course. »
Le cavalier y consentit, et vers l'arbre, ils partirent.
Un hurlement, une ruée, un souffle, le vent laissa le cavalier derrière de lui.
Mais, dans un éclair, un galop élégant, cheval et cavalier passèrent devant le vent.
Pendant un long moment, ils firent des va-et-vient, jusqu'à ce qu'enfin, l'esprit elfe arrive face à eux.
« Bien joué, dit l'esprit en soufflant. Je t'accorde ma grâce ainsi qu'à tous tes proches ».
Beirand et Narya prirent donc congé, conservant à jamais la faveur de la nymphe.
	[/text]
	[text]
		text = '
	[/text]
[/italic]```

**Comment by babaissarkar** [comment]
I wonder why the description text is inside `[italic]`. The English version doesn't have that.

**Comment by CelticMinstrel** [comment]
This is probably the cause:
https://github.com/wesnoth/wesnoth/blob/4062f579e3508854e2d3624eb1079d6e8f70cca1/po/wesnoth-units/fr.po#L3765-L3767

It's parsing that as a paragraph break, which it probably shouldn't in this case. I guess there should be logic somehow to not parse paragraph breaks inside an attribute value?

**Comment by babaissarkar** [comment]
Just curious, why is the french version italic while the normal version isn't? Was that intentional, or a leftover?

**Comment by babaissarkar** [comment]
converting to new markup stops the text from appearing.
![Screenshot from 2024-10-03 07-26-38](https://github.com/user-attachments/assets/fc98a8d0-06fa-4f28-bf52-ef2d2c6b3879)

**Comment by CelticMinstrel** [comment]
> converting to new markup stops the `text=` from appearing.

However, it shouldn't appear even if we don't convert to new markup, so that's not valid as a solution.

**Comment by babaissarkar** [comment]
> > converting to new markup stops the `text=` from appearing.
> 
> However, it shouldn't appear even if we don't convert to new markup, so that's not valid as a solution.

Can you fix that on the parser end?

**Comment by CelticMinstrel** [comment]
It probably shouldn't be that hard, since we've clearly identified the cause – just needs a new unit test, and some debugging. Well, I don't know how much it'll take to actually implement the fix though.

I probably won't get to it in the next couple of days, however. If someone else wants to take a shot at it before then, feel free.

**Comment by babaissarkar** [comment]
@Wedge009 how does the help browser look now with the latest master? I pushed a fix for the wrapping issue sometime ago.

**Comment by Wedge009** [comment]
It looks like the text area isn't sized quite right, not taking into account the vertical scroll-bar (it's an issue I've seen before with the Load Game screen). It still happens with scaling 1x because the end of the text is hidden by the vertical scroll-bar, although there is no horizontal scroll-bar in this case. (Edit: This first issue is tracked in #10261)
![image](https://github.com/user-attachments/assets/0e6fed81-f6f1-4ca8-9072-180cdf542bdd)

Back to the distorted rendering I showed earlier, I still get it on all of the first several elf units _except_ for the first one. Text might be a factor because if I change the language to `en_GB` the distortion is on all but the first _two_. Changing to scaling 1x didn't appear to make a difference.
![image](https://github.com/user-attachments/assets/0265610c-42f5-4b39-933b-9d0f4c60ae70)

Tested against 9f64e355f9f.

**Comment by Vultraz** [comment]
![image](https://github.com/user-attachments/assets/b5b1c819-55a8-4a51-b174-503e677883c5)

**Comment by Wedge009** [comment]
Darn, I can confirm that one - I remember adding those pages years ago.

A case of mark-up being handled differently in the new layout?

**Comment by babaissarkar** [comment]
> A case of mark-up being handled differently in the new layout?
Yeah, `<jump>` is removed, need to be converted to `<table></table>` markup.

**Comment by CelticMinstrel** [comment]
It would definitely be nice if the renderer didn't do insane things like that even _if_ the markup isn't quite what we want it to be…

**Comment by Wedge009** [comment]
- [x] I only noticed this while checking #9545: maybe not directly related, but there are spacing issues for translations where the replacement is much longer than the original:

  ![image](https://github.com/user-attachments/assets/9a8ba16f-d768-462b-8a7d-ced08328ccc0)

**Comment by CelticMinstrel** [comment]
Uhh… what's going on there? Doesn't it use the actual text in the columns to determine the column width? Is it somehow using the English text instead of the translated text?

**Comment by Wedge009** [comment]
I don't know what's going on. But to be clear, I'm looking at 'corps à corps', which is the translated text for mêlée. I didn't expect it to be wrapped around in this way.

**Comment by CelticMinstrel** [comment]
> But to be clear, I'm looking at 'corps à corps',

Yes, I got that. Even if the columns are set at those widths for some other reason (such as limited space), that behaviour is totally broken. The second "corps" should line up right beneath the crossed swords icon.

Also, aren't those icons the wrong colour? They should be the same colour as they are on the sidebar.

**Comment by Wedge009** [comment]
The colours seem to be consistent. I don't know what colour you expect the piercing icon to be.

**Comment by Wedge009** [comment]
1.18.3 release:
![image](https://github.com/user-attachments/assets/c59024a8-0c01-421f-8db3-93347e8d6d20)

1.19.5+dev:
![image](https://github.com/user-attachments/assets/c8345215-85bd-4e52-99b8-293cf0c4a46c)

**Comment by CelticMinstrel** [comment]
Just in case I wasn't clear, I was talking about the ranged/melee icons, not those icons.

I'm not sure there's a real issue having them be smaller, though at that size they should probably be moved down a little to line up better with the text's baseline.

**Comment by Wedge009** [comment]
I mentioned piercing before, so I thought you were referring to those. In both 1.18 and 1.19, the mêlée/ranged attack icons are black-and-white.

**Comment by babaissarkar** [comment]
> Uhh… what's going on there? Doesn't it use the actual text in the columns to determine the column width? Is it somehow using the English text instead of the translated text?

Table does calculate the width of its contents. My guess is that some other block is interfering with table's layouting.

**Comment by babaissarkar** [comment]
Also, @Wedge009 did you notice any improvements to the squeezing issue with recent commits? It should occur much less frequently now.

Checking shows that the squeezing happens only with pages with tables and is probably related to table's automatic width/height calculations.

**Comment by Wedge009** [comment]
I still notice it quite often, but the automatic calculation explanation sounds plausible.

**Comment by white-haired-uncle** [comment]
Smashed text, large spaces between tree view nodes, might not be wrapping correctly.

I may need to do a clean build here in case a local change has touched rich_label.  I don't think so, but I don't really get git, so maybe.

UMC, btw

![help](https://github.com/user-attachments/assets/cde51b1d-bbe7-4b61-970d-9e31a8336b93)

**Comment by babaissarkar** [comment]
The tree view space looks normal (Vultraz increased it a while ago)
The smashed text issue is already reported, but thanks.

**Comment by babaissarkar** [comment]
![Image](https://github.com/user-attachments/assets/b57a75e9-d3a5-4d74-bcd1-306e75c18f3d)

- [ ] Incorrect wrapping for table entries for some units. (Fighter, Footpad, perhaps others)

**Comment by Wedge009** [comment]
Seems to be related to the text and overall layout of the dialogue. I could replicate this for Footpad in English, but not in French (petite frappe).

**Comment by Wedge009** [comment]
#9886 visible in the images for my original report.

**Comment by babaissarkar** [comment]
> Seems to be related to the text and overall layout of the dialogue. I could replicate this for Footpad in English, but not in French (petite frappe).

https://github.com/wesnoth/wesnoth/issues/9417#issuecomment-2637501991 should be fixed by https://github.com/wesnoth/wesnoth/commit/98e4901a3ff691006317f0a0afb2715258efcb43.

**Comment by Vultraz** [comment]
Can we create sub-issues for whatever is left?

**Comment by Wedge009** [comment]
At e13629feec0, I retested the two specific issues in the original report (over-sized portrait and squashed display) and they seem to be okay. I updated that post accordingly.

That's not to say that the latter doesn't happen any more, but a review of elf and human units didn't show any squashed renderings for me - so maybe the overall situation has improved? If there are still occurrences, would be good to document them.

**Comment by Wedge009** [comment]
> converting to new markup stops the `text=` from appearing.

I separated the `text=` issue into #10838.

**Comment by Wedge009** [comment]
As best as I can tell, this issue doesn't have anything untracked/unresolved left in it. It should now just be a 'parent' tracker for all the sub-issues attached to it.

**Comment by babaissarkar** [comment]
> As best as I can tell, this issue doesn't have anything untracked/unresolved left in it. It should now just be a 'parent' tracker for all the sub-issues attached to it.

Changed issue type to Task.
